create extension if not exists "pgcrypto";
create table if not exists workspaces (id uuid primary key default gen_random_uuid(), name text not null, owner_id uuid not null, created_at timestamptz not null default now());
create table if not exists projects (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references workspaces(id) on delete cascade, name text not null, created_at timestamptz not null default now());
create table if not exists stores (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id) on delete cascade, name text, url text not null, market text, currency text, platform text, created_at timestamptz not null default now());
create table if not exists audit_runs (id uuid primary key default gen_random_uuid(), store_id uuid not null references stores(id) on delete cascade, source text not null check(source in ('web','extension','worker')), page_type text, score int, coverage int, status text not null default 'queued', report jsonb, created_at timestamptz not null default now());
create table if not exists competitors (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id) on delete cascade, store_url text not null, name text, classification text, match_score int, confidence_score int, signals jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists opportunities (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id) on delete cascade, title text not null, impact text, confidence text, evidence jsonb not null default '{}'::jsonb, status text not null default 'identified', created_at timestamptz not null default now());
create index if not exists idx_projects_workspace on projects(workspace_id);
create index if not exists idx_stores_project on stores(project_id);
create index if not exists idx_audits_store_created on audit_runs(store_id,created_at desc);
create index if not exists idx_competitors_project on competitors(project_id);
