import 'server-only';

type Provider='gemini'|'groq'|'openrouter';
export type StructuredResult<T>={provider:Provider;model:string;data:T;errors:string[]};
const safeJson=(text:string)=>{try{return JSON.parse(text)}catch{const start=text.indexOf('{'),end=text.lastIndexOf('}');if(start>=0&&end>start)try{return JSON.parse(text.slice(start,end+1))}catch{};return null}};

export async function askStructuredNOVA<T>({system,prompt,maxTokens=3500}:{system:string;prompt:string;maxTokens?:number}):Promise<StructuredResult<T>>{
 const errors:string[]=[];
 if(process.env.GEMINI_API_KEY){try{const model=process.env.GEMINI_MODEL||'gemini-2.5-flash';const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(process.env.GEMINI_API_KEY)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:.15,responseMimeType:'application/json',maxOutputTokens:maxTokens}}),signal:AbortSignal.timeout(24000)});if(!r.ok)throw new Error(`Gemini ${r.status}`);const j:any=await r.json();const text=j?.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||'').join('')||'';const data=safeJson(text);if(!data)throw new Error('Gemini returned invalid JSON');return {provider:'gemini',model,data,errors}}catch(e:any){errors.push(String(e?.message||e))}}
 if(process.env.GROQ_API_KEY){try{const model=process.env.GROQ_MODEL||'llama-3.3-70b-versatile';const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${process.env.GROQ_API_KEY}`},body:JSON.stringify({model,temperature:.15,max_completion_tokens:maxTokens,messages:[{role:'system',content:system},{role:'user',content:`${prompt}\nReturn valid JSON only.`}]}),signal:AbortSignal.timeout(24000)});if(!r.ok)throw new Error(`Groq ${r.status}`);const j:any=await r.json();const data=safeJson(j?.choices?.[0]?.message?.content||'');if(!data)throw new Error('Groq returned invalid JSON');return {provider:'groq',model,data,errors}}catch(e:any){errors.push(String(e?.message||e))}}
 if(process.env.OPENROUTER_API_KEY){try{const model=process.env.OPENROUTER_MODEL||'openrouter/free';const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${process.env.OPENROUTER_API_KEY}`,'HTTP-Referer':process.env.NEXT_PUBLIC_APP_URL||'https://nova-eynk.vercel.app','X-Title':'NOVA'},body:JSON.stringify({model,temperature:.15,max_tokens:maxTokens,messages:[{role:'system',content:system},{role:'user',content:`${prompt}\nReturn valid JSON only.`}]}),signal:AbortSignal.timeout(28000)});if(!r.ok)throw new Error(`OpenRouter ${r.status}`);const j:any=await r.json();const data=safeJson(j?.choices?.[0]?.message?.content||'');if(!data)throw new Error('OpenRouter returned invalid JSON');return {provider:'openrouter',model,data,errors}}catch(e:any){errors.push(String(e?.message||e))}}
 throw new Error(`No AI provider returned structured output${errors.length?`: ${errors.join(' · ')}`:''}`);
}
