import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
test('project navigation exposes buyer persona and global Chat with NOVA',()=>{const s=read('apps/web/components/Sidebar.tsx');assert.match(s,/Buyer Persona/);assert.match(s,/ChatWithNOVA/);assert.match(read('apps/web/components/ChatWithNOVA.tsx'),/Project-aware AI/)});
test('persona intelligence uses transient source files and evidence-grounded unknown rules',()=>{const e=read('apps/web/lib/persona/engine.ts'),ui=read('apps/web/components/BuyerPersonaLab.tsx');assert.match(e,/Never invent demographics/);assert.match(e,/Unknown stays Unknown/);assert.match(e,/aggregate only/);assert.match(ui,/Raw files are analyzed in-memory/)});
test('buyer persona output includes required intelligence layers',()=>{const e=read('apps/web/lib/persona/engine.ts');for(const x of ['segments','personas','behaviorPatterns','voiceOfCustomer','marketingIntelligence','geoInsights','productAffinities','nextDataToCollect'])assert.match(e,new RegExp(x))});
test('AI chat persists history and can use persona context',()=>{const r=read('apps/web/app/api/projects/[id]/ai/route.ts'),c=read('apps/web/lib/ai/context.ts');assert.match(r,/ai_chat_messages/);assert.match(r,/pageContext/);assert.match(c,/buyerPersona/);assert.match(c,/persona_reports/)});
test('competitor AI can veto but cannot promote a failed deterministic gate',()=>{const a=read('apps/web/app/actions/competitors.ts'),ai=read('apps/web/lib/ai/competitor-discovery.ts');assert.match(a,/if\(automatic&&!gate\.accepted\)return/);assert.match(a,/aiReviewCompetitorEvidence/);assert.match(a,/aiReview\?\.verdict==='reject'/);assert.match(ai,/must NEVER promote/)});
test('migration 012 protects chat and persona data with RLS',()=>{const s=read('infra/supabase/012_ai_os_persona_chat.sql');assert.match(s,/create table if not exists public\.ai_chat_messages/);assert.match(s,/create table if not exists public\.persona_reports/);assert.match(s,/enable row level security/g);assert.match(s,/can_access_project/)});
test('50 phase implementation document is included',()=>{const d=read('docs/NOVA-1.6-AI-OPERATING-SYSTEM-50-PHASES.md');for(let i=1;i<=50;i++)assert.match(d,new RegExp(`\\b${i}\\.`))});
