import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';const read=p=>fs.readFileSync(p,'utf8');
test('NOVA 1.1 migration adds intelligence persistence',()=>{const s=read('infra/supabase/010_nova_11_intelligence.sql');for(const x of ['product_snapshots','notifications','report_shares','decision_score','effort'])assert.match(s,new RegExp(x))});
test('monitoring v2 writes product snapshots and notifications',()=>{const s=read('apps/web/app/api/cron/monitor/route.ts');assert.match(s,/product_snapshots/);assert.match(s,/notifications/);assert.match(s,/pricing/);assert.match(s,/assortment/)});
test('product intelligence exposes pricing and assortment comparisons',()=>{const s=read('apps/web/app/projects/[id]/products/page.tsx');assert.match(s,/Pricing & assortment/);assert.match(s,/Price position/);assert.match(s,/ASSORTMENT GAPS/)});
test('opportunity engine v2 considers effort and decision score',()=>{const s=read('apps/web/lib/intelligence/opportunity.ts');assert.match(s,/decisionScore/);assert.match(s,/Quick Win/);assert.match(read('apps/web/app/actions/benchmark.ts'),/decision_score/)});
test('NOVA Analyst is grounded and zero-cost',()=>{const s=read('apps/web/app/projects/[id]/analyst/page.tsx');assert.match(s,/zero-cost analyst/i);assert.match(s,/does not require a paid AI API/i);assert.match(read('apps/web/lib/intelligence/analyst.ts'),/Pricing position/)});
test('reports can create read-only share links',()=>{assert.match(read('apps/web/app/actions/intelligence.ts'),/report_shares/);assert.match(read('apps/web/app/share/[token]/page.tsx'),/Shared intelligence report/)});
test('command center includes guided onboarding',()=>{const s=read('apps/web/app/projects/[id]/page.tsx');assert.match(s,/Get NOVA to full intelligence/);assert.match(s,/Monitoring enabled/);assert.match(s,/Product Intelligence/)});
test('sidebar exposes 1.1 surfaces',()=>{const s=read('apps/web/components/Sidebar.tsx');for(const x of ['Products','Analyst','Notifications'])assert.match(s,new RegExp(x))});
