import 'server-only';
import {createSupabaseAdminClient} from '../supabase/admin';
import {isSupabaseConfigured} from '../config';
import {aiProviderStatus} from '../ai/router';

type State='healthy'|'warning'|'error'|'not_configured';
export type HealthItem={id:string;label:string;group:string;state:State;detail:string;latencyMs?:number;recommendation?:string};
export type SystemReport={generatedAt:string;overall:State;score:number;items:HealthItem[];issues:HealthItem[];ai:ReturnType<typeof aiProviderStatus> & {providers:HealthItem[]}};
const timed=async<T>(fn:()=>Promise<T>)=>{const s=Date.now();try{return {ok:true as const,value:await fn(),ms:Date.now()-s}}catch(error:any){return {ok:false as const,error:String(error?.message||error),ms:Date.now()-s}}};
async function probe(url:string,init?:RequestInit){return timed(async()=>{const r=await fetch(url,{...init,cache:'no-store',signal:AbortSignal.timeout(6500)});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.status})}
export async function getSystemReport():Promise<SystemReport>{const items:HealthItem[]=[];if(!isSupabaseConfigured){items.push({id:'supabase-env',label:'Supabase core',group:'Core',state:'error',detail:'Public Supabase environment variables are missing',recommendation:'Add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in Vercel'});}else{const db=await timed(async()=>{const a=createSupabaseAdminClient();const {error}=await a.from('projects').select('id',{head:true,count:'exact'}).limit(1);if(error)throw error;return true});items.push({id:'database',label:'Database',group:'Core',state:db.ok?'healthy':'error',detail:db.ok?'Supabase database is reachable':`Database probe failed: ${db.error}`,latencyMs:db.ms,recommendation:db.ok?undefined:'Check SUPABASE_SERVICE_ROLE_KEY and migrations'});const auth=await timed(async()=>{const a=createSupabaseAdminClient();await a.auth.admin.listUsers({page:1,perPage:1});return true});items.push({id:'auth',label:'Authentication',group:'Core',state:auth.ok?'healthy':'error',detail:auth.ok?'Supabase Auth admin API is reachable':`Auth probe failed: ${auth.error}`,latencyMs:auth.ms,recommendation:auth.ok?undefined:'Verify service role key and Supabase Auth configuration'});try{const s=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/auth/v1/settings`,{headers:{apikey:process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||''},cache:'no-store',signal:AbortSignal.timeout(5000)});const j:any=await s.json();const google=Boolean(j?.external?.google);items.push({id:'google-auth',label:'Google Sign in',group:'Integrations',state:google?'healthy':'warning',detail:google?'Google OAuth provider is enabled':'Google OAuth provider is not enabled',recommendation:google?undefined:'Enable Google provider in Supabase Authentication'});}catch{items.push({id:'google-auth',label:'Google Sign in',group:'Integrations',state:'warning',detail:'Could not verify Google OAuth settings'})}}
const providers:HealthItem[]=[];if(process.env.GEMINI_API_KEY){const p=await probe(`https://generativelanguage.googleapis.com/v1beta/models?key=${encodeURIComponent(process.env.GEMINI_API_KEY)}`);providers.push({id:'gemini',label:'Gemini',group:'AI',state:p.ok?'healthy':'warning',detail:p.ok?'Gemini API key is valid':`Gemini probe failed: ${p.error}`,latencyMs:p.ms,recommendation:p.ok?undefined:'Check GEMINI_API_KEY or model quota'});}else providers.push({id:'gemini',label:'Gemini',group:'AI',state:'not_configured',detail:'No Gemini key configured'});if(process.env.GROQ_API_KEY){const p=await probe('https://api.groq.com/openai/v1/models',{headers:{authorization:`Bearer ${process.env.GROQ_API_KEY}`}});providers.push({id:'groq',label:'Groq',group:'AI',state:p.ok?'healthy':'warning',detail:p.ok?'Groq API key is valid':`Groq probe failed: ${p.error}`,latencyMs:p.ms,recommendation:p.ok?undefined:'Check GROQ_API_KEY or provider status'});}else providers.push({id:'groq',label:'Groq',group:'AI',state:'not_configured',detail:'No Groq key configured'});if(process.env.OPENROUTER_API_KEY){const p=await probe('https://openrouter.ai/api/v1/models',{headers:{authorization:`Bearer ${process.env.OPENROUTER_API_KEY}`}});providers.push({id:'openrouter',label:'OpenRouter Free',group:'AI',state:p.ok?'healthy':'warning',detail:p.ok?'OpenRouter API is reachable':`OpenRouter probe failed: ${p.error}`,latencyMs:p.ms,recommendation:p.ok?undefined:'Check OPENROUTER_API_KEY'});}else providers.push({id:'openrouter',label:'OpenRouter Free',group:'AI',state:'not_configured',detail:'Optional free-model fallback is not configured'});items.push(...providers);items.push({id:'search',label:'Competitor Search',group:'Integrations',state:process.env.DISABLE_FREE_DISCOVERY==='true'?'warning':'healthy',detail:process.env.SEARXNG_URL?'Custom SearXNG instance configured':'Free SearXNG + DuckDuckGo fallback enabled'});items.push({id:'monitoring',label:'Monitoring Scheduler',group:'Integrations',state:process.env.CRON_SECRET?'healthy':'warning',detail:process.env.CRON_SECRET?'Cron secret configured':'CRON_SECRET not configured',recommendation:process.env.CRON_SECRET?undefined:'Add CRON_SECRET if you want protected scheduled monitoring'});items.push({id:'extension',label:'Chrome Extension API',group:'Integrations',state:'healthy',detail:'Extension ingestion endpoint is included in this build'});
if(isSupabaseConfigured){const chat=await timed(async()=>{const a=createSupabaseAdminClient();const {error}=await a.from('ai_chat_messages').select('id',{head:true,count:'exact'}).limit(1);if(error)throw error;return true});items.push({id:'ai-chat',label:'Chat with NOVA',group:'AI Surfaces',state:chat.ok?'healthy':'warning',detail:chat.ok?'Project-aware AI chat persistence is ready':`AI chat table probe failed: ${chat.error}`,latencyMs:chat.ms,recommendation:chat.ok?undefined:'Run migration 012_ai_os_persona_chat.sql'});const persona=await timed(async()=>{const a=createSupabaseAdminClient();const {error}=await a.from('persona_reports').select('id',{head:true,count:'exact'}).limit(1);if(error)throw error;return true});items.push({id:'buyer-persona',label:'Buyer Persona Intelligence',group:'AI Surfaces',state:persona.ok?'healthy':'warning',detail:persona.ok?'Persona report persistence is ready':`Persona table probe failed: ${persona.error}`,latencyMs:persona.ms,recommendation:persona.ok?undefined:'Run migration 012_ai_os_persona_chat.sql'});}const issues=items.filter(x=>x.state==='error'||x.state==='warning');const errors=items.filter(x=>x.state==='error').length;const warnings=items.filter(x=>x.state==='warning').length;const score=Math.max(0,100-errors*22-warnings*7);const overall:State=errors?'error':warnings?'warning':'healthy';return {generatedAt:new Date().toISOString(),overall,score,items,issues,ai:{...aiProviderStatus(),providers}}}
