import 'server-only';
import {runNOVAWorkflowTask} from '../ai/orchestrator';

export type PersonaInputFile={name:string;type?:string;text:string};
export type PersonaSegment={name:string;share?:string;description:string;signals:string[];products:string[];regions:string[];priceSensitivity:string;purchaseTriggers:string[];objections:string[];confidence:number};
export type PersonaReport={executiveSummary:string;dataQuality:{score:number;strengths:string[];gaps:string[]};segments:PersonaSegment[];personas:{name:string;segment:string;whoTheyAre:string;behavior:string[];motivations:string[];objections:string[];messaging:string[];offers:string[];channels:string[];unknowns:string[];confidence:number}[];behaviorPatterns:{pattern:string;evidence:string;confidence:number}[];voiceOfCustomer:{theme:string;phrases:string[];meaning:string;confidence:number}[];marketingIntelligence:{angle:string;why:string;audience:string;confidence:number}[];geoInsights:{region:string;insight:string;confidence:number}[];productAffinities:{products:string[];insight:string;confidence:number}[];competitiveBridges:{segment:string;customerEvidence:string;competitorEvidence:string;implication:string;recommendedTest:string;confidence:number}[];evidenceNotes:string[];nextDataToCollect:string[]};

function lines(text:string){return text.split(/\r?\n/).filter(Boolean)}
function summarizeFile(f:PersonaInputFile){const raw=f.text.slice(0,120000),ls=lines(raw),first=ls[0]||'',delim=first.includes('\t')?'\t':first.includes(';')?';':',';const headers=first.split(delim).map(x=>x.trim().replace(/^['"]|['"]$/g,''));return {name:f.name,type:f.type||'',characters:f.text.length,rows:Math.max(0,ls.length-1),headers:headers.slice(0,40),sample:ls.slice(0,16).join('\n').slice(0,9000)}}
function sourceQuality(files:PersonaInputFile[]){const names=files.map(x=>x.name.toLowerCase()).join(' ');const strengths:string[]=[];if(/order|sales|transaction/.test(names))strengths.push('Transactional purchase data supplied');if(/review|feedback|survey/.test(names))strengths.push('Voice-of-customer evidence supplied');if(/city|region|geo/.test(names))strengths.push('Geographic evidence supplied');if(/support|whatsapp|chat/.test(names))strengths.push('Support/conversation evidence supplied');if(/return|refund/.test(names))strengths.push('Returns/refunds evidence supplied');const score=Math.min(95,30+files.length*8+strengths.length*8);return {score,strengths,gaps:['Age/gender/lifestyle must remain Unknown unless explicitly evidenced','Causation must not be inferred from correlation','Small samples should be treated as directional'].filter(Boolean)}}

export async function buildPersonaReport(files:PersonaInputFile[],notes:string,projectContext:any){
 const summaries=files.map(summarizeFile);const quality=sourceQuality(files);
 const system=`You are NOVA Buyer Persona Intelligence. Build evidence-based customer intelligence from USER-SUPPLIED data only. Never invent demographics, gender, age, lifestyle, income, motivations, cities, channels or psychology. Unknown stays Unknown. Separate observed facts from inference. Use sample size/data quality in confidence. Do not expose personal names, emails, phone numbers or individual identifiers in outputs; aggregate only. Return JSON matching the requested schema exactly.`;
 const schema=`{"executiveSummary":"", "dataQuality":{"score":0,"strengths":[],"gaps":[]}, "segments":[{"name":"","share":"Unknown unless calculable","description":"","signals":[],"products":[],"regions":[],"priceSensitivity":"Unknown/Low/Medium/High with evidence","purchaseTriggers":[],"objections":[],"confidence":0}], "personas":[{"name":"descriptive segment name, not a fake person","segment":"","whoTheyAre":"","behavior":[],"motivations":[],"objections":[],"messaging":[],"offers":[],"channels":[],"unknowns":[],"confidence":0}], "behaviorPatterns":[{"pattern":"","evidence":"","confidence":0}], "voiceOfCustomer":[{"theme":"","phrases":["short paraphrases, not long quotes"],"meaning":"","confidence":0}], "marketingIntelligence":[{"angle":"","why":"","audience":"","confidence":0}], "geoInsights":[{"region":"","insight":"","confidence":0}], "productAffinities":[{"products":[],"insight":"","confidence":0}], "competitiveBridges":[{"segment":"","customerEvidence":"","competitorEvidence":"","implication":"","recommendedTest":"","confidence":0}], "evidenceNotes":[], "nextDataToCollect":[]}`;
 const prompt=`PROJECT + COMPETITIVE CONTEXT (store/competitor facts are context, not customer facts unless supported by uploaded customer data):\n${JSON.stringify(projectContext).slice(0,12000)}\n\nUSER NOTES:\n${notes.slice(0,5000)||'None'}\n\nSOURCE METADATA + SAMPLES:\n${JSON.stringify(summaries,null,2).slice(0,52000)}\n\nBaseline source-quality assessment: ${JSON.stringify(quality)}\n\nCreate a rigorous report. Prefer 2-5 meaningful behavioral segments, but return fewer when evidence is insufficient. In competitiveBridges, connect customer evidence to supplied VERIFIED competitor/CRO evidence only when both sides are present; otherwise return an empty array. Never use competitor behavior as proof of customer motivation. Confidence is 0-100. Schema:\n${schema}`;
 const ai=await runNOVAWorkflowTask<PersonaReport>('persona',{system,prompt,maxTokens:5200});
 const report:any=ai.data;report.dataQuality=report.dataQuality||quality;report.dataQuality.score=Math.min(Number(report.dataQuality.score||quality.score),quality.score+5);return {provider:ai.provider,model:ai.model,report:report as PersonaReport,sourceSummary:{files:summaries.map(({sample,...x})=>x),quality}};
}
