import 'server-only';
import dns from 'node:dns/promises';
import net from 'node:net';

type Status='pass'|'warn'|'fail'|'review'|'unknown';
export type AuditCheck={key:string;title:string;category:string;status:Status;weight:number;evidence:string[];recommendation?:string;reference?:string};
export type ServerAuditReport={version:string;url:string;finalUrl:string;page:{type:string;confidence:number;evidence:string[]};site:{title:string|null;platform:string|null;language:string|null};checks:AuditCheck[];performance:{fetchMs:number;htmlBytes:number};createdAt:string};

const PRIVATE_V4=[/^10\./,/^127\./,/^169\.254\./,/^192\.168\./,/^172\.(1[6-9]|2\d|3[01])\./,/^0\./];
function isPrivateIp(ip:string){if(net.isIPv4(ip))return PRIVATE_V4.some(r=>r.test(ip));if(net.isIPv6(ip))return ip==='::1'||ip.startsWith('fc')||ip.startsWith('fd')||ip.startsWith('fe80:');return true;}
async function assertPublicUrl(raw:string){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol))throw new Error('Only http/https URLs are supported.');if(['localhost','0.0.0.0'].includes(u.hostname))throw new Error('Local addresses are not allowed.');const addresses=await dns.lookup(u.hostname,{all:true});if(!addresses.length||addresses.some(x=>isPrivateIp(x.address)))throw new Error('Private or unresolved destinations are not allowed.');return u;}
function text(html:string){return html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim();}
function has(re:RegExp,s:string){return re.test(s)}
function count(re:RegExp,s:string){return (s.match(re)||[]).length}
function meta(html:string,name:string){const a=new RegExp(`<meta[^>]+(?:name|property)=["']${name}["'][^>]+content=["']([^"']*)["'][^>]*>`,`i`).exec(html);const b=new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+(?:name|property)=["']${name}["'][^>]*>`,`i`).exec(html);return (a?.[1]||b?.[1]||'').trim()||null}
function title(html:string){return /<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1]?.replace(/\s+/g,' ').trim()||null}
function detectPlatform(html:string){if(/cdn\.shopify\.com|Shopify\.theme|shopify-section/i.test(html))return 'Shopify';if(/salla\.sa|salla\.cloud|salla-/i.test(html))return 'Salla';if(/zid\.store|zid\.sa/i.test(html))return 'Zid';if(/woocommerce|wp-content\/plugins\/woocommerce/i.test(html))return 'WooCommerce';return null}
function detectPage(url:string,html:string,body:string){const signals:{type:string;score:number;why:string[]}[]=[
 {type:'PDP',score:0,why:[]},{type:'PLP',score:0,why:[]},{type:'CART',score:0,why:[]},{type:'HOMEPAGE',score:0,why:[]}];
 const p=new URL(url).pathname.toLowerCase();const add=(t:string,n:number,w:string)=>{const x=signals.find(s=>s.type===t)!;x.score+=n;x.why.push(w)};
 if(/^\/?$/.test(p))add('HOMEPAGE',70,'root path');
 if(/\/products?\/|\/p\//.test(p))add('PDP',55,'product-like URL'); if(/add to (cart|bag)|أضف (إلى|الى) (السلة|الحقيبة)/i.test(body))add('PDP',30,'purchase CTA detected'); if(/product:price:amount|Product\"/i.test(html))add('PDP',20,'product structured data');
 if(/\/collections?\/|\/categor(y|ies)\/|\/shop\/?/.test(p))add('PLP',50,'collection/category URL'); if(count(/product-card|product-item|grid-product/gi,html)>=3)add('PLP',35,'multiple product cards');
 if(/\/cart\/?/.test(p))add('CART',75,'cart URL'); if(/subtotal|order summary|سلة التسوق|الإجمالي الفرعي/i.test(body))add('CART',25,'cart language detected');
 const best=signals.sort((a,b)=>b.score-a.score)[0];return {type:best.score>=35?best.type:'UNKNOWN',confidence:Math.min(99,best.score),evidence:best.why};
}
function c(key:string,title:string,category:string,status:Status,weight:number,evidence:string[],recommendation?:string):AuditCheck{return {key,title,category,status,weight,evidence,recommendation}}
function buildChecks(pageType:string,html:string,body:string):AuditCheck[]{const checks:AuditCheck[]=[];const h1=count(/<h1\b/gi,html);const desc=meta(html,'description');
 checks.push(c('document-title','Descriptive page title','SEO/UX',title(html)?'pass':'fail',4,title(html)?[`Title found: ${title(html)!.slice(0,90)}`]:['No <title> found'],'Add a clear, page-specific document title.'));
 checks.push(c('meta-description','Meta description','SEO/UX',desc?'pass':'warn',2,desc?[`Description length: ${desc.length}`]:['No meta description detected'],'Add a concise meta description for search snippets.'));
 checks.push(c('viewport','Mobile viewport','UX',/name=["']viewport["']/i.test(html)?'pass':'fail',7,[/name=["']viewport["']/i.test(html)?'Viewport meta detected':'Viewport meta missing'],'Add a responsive viewport meta tag.'));
 checks.push(c('h1','Primary heading hierarchy','UX',h1===1?'pass':h1===0?'fail':'warn',6,[`${h1} H1 element(s) found`],h1===0?'Provide one clear primary heading.':'Keep one dominant H1 per page.'));
 if(pageType==='PDP'){
  const hasPrice=/(?:SAR|AED|USD|EGP|ر\.س|د\.إ|ج\.م|\$)\s?[\d,.]+|[\d,.]+\s?(?:SAR|AED|USD|EGP|ر\.س|د\.إ|ج\.م)/i.test(body)||/price/i.test(html);
  const atc=/add to (cart|bag)|أضف (إلى|الى) (السلة|الحقيبة)|اضف للسلة/i.test(body);
  const aggregate=/aggregateRating/i.test(html);const reviewCount=/reviewCount["']?\s*[:=]\s*["']?([1-9]\d*)/i.exec(html)?.[1];const reviewBlocks=count(/class=["'][^"']*(review|testimonial)[^"']*["']/gi,html);
  checks.push(c('price','Visible price signal','Purchase',hasPrice?'pass':'fail',10,[hasPrice?'Price signal detected in server HTML':'No reliable price signal detected'],'Show the current selling price prominently near the purchase decision area.'));
  checks.push(c('atc','Add-to-cart capability','Purchase',atc?'pass':'fail',12,[atc?'Purchase CTA text detected':'No Add to Cart/Bag CTA text detected'],'Provide a clear primary purchase CTA.'));
  checks.push(c('reviews-actual','Actual review content','Trust',reviewCount||reviewBlocks>=2||aggregate?'pass':/review|rating|تقييم/i.test(body)?'review':'fail',8,[reviewCount?`Structured reviewCount: ${reviewCount}`:aggregate?'AggregateRating structured data detected':reviewBlocks?`${reviewBlocks} review-like blocks detected`:/review|rating|تقييم/i.test(body)?'Review language exists, but actual review content could not be proven':'No actual reviews proven'],'Collect and render genuine customer reviews; do not rely on an empty reviews section.'));
  checks.push(c('reviews-near-decision','Social proof near purchase area','Trust','unknown',9,['Server HTML cannot reliably prove visual proximity/visibility near ATC'],'Verify in a rendered browser that rating and review count are visible near title/price/ATC.'));
  checks.push(c('shipping','Shipping reassurance','Trust',/shipping|delivery|توصيل|شحن/i.test(body)?'pass':'warn',7,[/shipping|delivery|توصيل|شحن/i.test(body)?'Shipping/delivery language detected':'No shipping/delivery language detected'],'Surface delivery timing or shipping reassurance near the buying decision.'));
  checks.push(c('returns','Returns/exchange reassurance','Trust',/return|exchange|استرجاع|استبدال/i.test(body)?'pass':'warn',6,[/return|exchange|استرجاع|استبدال/i.test(body)?'Returns/exchange language detected':'No returns/exchange language detected'],'Make return/exchange terms easy to find before purchase.'));
  checks.push(c('media','Product media depth','Merchandising',count(/<img\b/gi,html)>=4?'pass':'warn',5,[`${count(/<img\b/gi,html)} image elements found in HTML`],'Use multiple high-quality product views; add video where it reduces uncertainty.'));
 }
 if(pageType==='PLP'){const cards=count(/product-card|product-item|grid-product/gi,html);checks.push(c('product-grid','Product listing detected','Merchandising',cards>=3?'pass':'review',9,[`${cards} product-card signals detected`],'Ensure the listing clearly exposes products and core decision information.'));checks.push(c('filtering','Filtering/sorting capability','UX',/filter|sort|تصفية|ترتيب/i.test(body)?'pass':'warn',7,[/filter|sort|تصفية|ترتيب/i.test(body)?'Filter/sort language detected':'Filter/sort capability not proven'],'Provide useful filtering and sorting for larger catalogs.'));}
 if(pageType==='HOMEPAGE'){checks.push(c('navigation','Primary navigation','UX',/<nav\b/i.test(html)?'pass':'review',7,[/<nav\b/i.test(html)?'NAV element detected':'Semantic navigation not proven'],'Provide clear access to major shopping categories.'));checks.push(c('search','Site search capability','UX',/type=["']search["']|search/i.test(html)?'pass':'warn',5,[/type=["']search["']|search/i.test(html)?'Search signal detected':'Search not proven'],'Make product search easy to access for returning/high-intent visitors.'));}
 return checks;}
export async function scanUrl(raw:string):Promise<ServerAuditReport>{const u=await assertPublicUrl(raw);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);const started=Date.now();try{const res=await fetch(u,{redirect:'follow',signal:controller.signal,headers:{'user-agent':'NOVA-AuditBot/1.0 (+https://nova.local)','accept':'text/html,application/xhtml+xml'}});if(!res.ok)throw new Error(`Target returned HTTP ${res.status}.`);const ct=res.headers.get('content-type')||'';if(!ct.includes('text/html')&&!ct.includes('application/xhtml+xml'))throw new Error('Target did not return an HTML page.');const html=(await res.text()).slice(0,2_500_000);const body=text(html);const finalUrl=res.url||u.toString();const page=detectPage(finalUrl,html,body);return {version:'1.0',url:u.toString(),finalUrl,page,site:{title:title(html),platform:detectPlatform(html),language:/<html[^>]+lang=["']([^"']+)/i.exec(html)?.[1]||null},checks:buildChecks(page.type,html,body),performance:{fetchMs:Date.now()-started,htmlBytes:Buffer.byteLength(html)},createdAt:new Date().toISOString()};}finally{clearTimeout(timer)}}
