import Link from 'next/link';
import {redirect} from 'next/navigation';
import {AdminSidebar} from '../../../components/AdminSidebar';
import {getCurrentUserRole} from '../../../lib/admin';
import {getSystemReport} from '../../../lib/system/status';

export default async function AdminAI(){
 const {user,isSuperAdmin}=await getCurrentUserRole();if(!user)redirect('/login');if(!isSuperAdmin)redirect('/dashboard');
 const report=await getSystemReport();const ai=report.items.filter(i=>i.group==='AI');const surfaces=report.items.filter(i=>i.group==='AI Surfaces');const integrations=report.items.filter(i=>i.group==='Integrations');
 return <main className="shell adminShell"><AdminSidebar/><section className="workspace adminWorkspace"><header className="pageHeader adminPageHeader"><div><p className="eyebrow">INTELLIGENCE INFRASTRUCTURE</p><h1>AI & integrations</h1><p className="muted">Provider chain, intelligence surfaces and fallback visibility</p></div><Link className="ghost" href="/admin/status">Open full diagnostics</Link></header><section className="adminAiHero"><div><span>Current AI route</span><strong>{report.ai.primary}</strong><small>Fallback chain: Gemini → Groq → OpenRouter Free → NOVA Evidence Engine</small></div><div><span>Platform health</span><strong>{report.score}/100</strong><small>{report.issues.length} issues detected</small></div></section><div className="adminAiGrid">{ai.map(item=><article className="adminAiCard" key={item.id}><div><span className={`healthDot ${item.state}`}/><b>{item.label}</b><em>{item.state.replace('_',' ')}</em></div><p>{item.detail}</p><small>{item.latencyMs?`${item.latencyMs} ms response`:(item.recommendation||'Ready as configured')}</small></article>)}</div><article className="adminSurface"><div className="adminSectionHead"><div><p className="eyebrow">AI SURFACES</p><h2>Intelligence across NOVA</h2><p>Project chat, buyer persona and grounded AI feature readiness</p></div></div><div className="adminIntegrationGrid">{surfaces.map(item=><div key={item.id}><span className={`healthDot ${item.state}`}/><div><b>{item.label}</b><small>{item.detail}</small></div><em>{item.state.replace('_',' ')}</em></div>)}</div></article><article className="adminSurface"><div className="adminSectionHead"><div><p className="eyebrow">INTEGRATIONS</p><h2>Connected services</h2><p>Operational readiness across NOVA</p></div></div><div className="adminIntegrationGrid">{integrations.map(item=><div key={item.id}><span className={`healthDot ${item.state}`}/><div><b>{item.label}</b><small>{item.detail}</small></div><em>{item.state.replace('_',' ')}</em></div>)}</div></article></section></main>
}
