import {redirect} from 'next/navigation';
import {AdminSidebar} from '../../../components/AdminSidebar';
import {getCurrentUserRole} from '../../../lib/admin';
import {getAdminDashboardData} from '../../../lib/admin-dashboard';
const DAY=86_400_000;
const date=(v?:string|null)=>v?new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'—';
const relative=(v?:string|null)=>{if(!v)return 'Never';const d=Date.now()-new Date(v).getTime();if(d<DAY)return 'Today';if(d<7*DAY)return `${Math.max(1,Math.floor(d/DAY))}d ago`;return date(v)};
export default async function AdminUsers(){const {user,isSuperAdmin}=await getCurrentUserRole();if(!user)redirect('/login');if(!isSuperAdmin)redirect('/dashboard');const d=await getAdminDashboardData();return <main className="shell adminShell"><AdminSidebar/><section className="workspace adminWorkspace"><header className="pageHeader adminPageHeader"><div><p className="eyebrow">USER INTELLIGENCE</p><h1>Users</h1><p className="muted">Account growth, activation, engagement and ownership</p></div><span className="adminCountBadge">{d.users.length} accounts</span></header><div className="adminMiniMetrics"><Mini label="New · 7d" value={d.metrics.new7}/><Mini label="Active · 7d" value={d.metrics.active7}/><Mini label="Returning" value={d.metrics.returningUsers}/><Mini label="Pending confirm" value={d.metrics.pendingUsers}/></div><article className="adminSurface"><div className="adminSectionHead"><div><h2>User directory</h2><p>Every registered account with adoption and sign-in detail</p></div></div><div className="adminTableWrap"><table className="adminTable adminUsersTable"><thead><tr><th>User</th><th>Role</th><th>Joined</th><th>Last sign in</th><th>Status</th><th>Provider</th><th>Workspaces</th><th>Projects</th><th>Stores</th></tr></thead><tbody>{d.users.map((u:any)=>{const s=d.userStats.get(u.id)||{workspaces:0,projects:0,stores:0};const providers=(u.app_metadata?.providers||[u.app_metadata?.provider||'email']).filter(Boolean).join(', ');const root=d.roleMap.get(u.id)==='super_admin';return <tr key={u.id}><td><div className="adminIdentity"><span className="identityDot">{(u.email||'?')[0].toUpperCase()}</span><div><b>{u.user_metadata?.full_name||u.email}</b><small>{u.email}</small></div></div></td><td><span className={root?'rolePill root':'rolePill'}>{root?'Super Admin':'User'}</span></td><td>{date(u.created_at)}</td><td>{relative(u.last_sign_in_at)}</td><td><span className={u.email_confirmed_at?'accountState confirmed':'accountState'}>{u.email_confirmed_at?'Confirmed':'Pending'}</span></td><td>{providers}</td><td>{s.workspaces}</td><td>{s.projects}</td><td>{s.stores}</td></tr>})}</tbody></table></div></article></section></main>}
function Mini({label,value}:{label:string,value:string|number}){return <article><span>{label}</span><strong>{value}</strong></article>}
