import {notFound,redirect} from 'next/navigation';
import {Sidebar} from '../../../../components/Sidebar';
import {createSupabaseServerClient} from '../../../../lib/supabase/server';
import {isSupabaseConfigured} from '../../../../lib/config';
import {assortmentGap,pricingPosition} from '../../../../lib/intelligence/product';
import {captureProductIntelligence} from '../../../actions/intelligence';

export default async function Products({params}:{params:Promise<{id:string}>}){
 const {id}=await params;if(!isSupabaseConfigured)redirect('/dashboard');const supabase=await createSupabaseServerClient();
 const {data:p}=await supabase.from('projects').select('id,name,stores(url,profile),competitors(id,name,store_url,profile,match_score,classification,status),product_snapshots(id,captured_at)').eq('id',id).maybeSingle();if(!p)notFound();
 const store:any=Array.isArray((p as any).stores)?(p as any).stores[0]:(p as any).stores;const own:any=store?.profile||{};const comps=((p as any).competitors||[]).filter((x:any)=>x.status!=='rejected'&&x.profile).sort((a:any,b:any)=>(b.match_score||0)-(a.match_score||0));
 const profiles=comps.map((x:any)=>x.profile||{});const pricing=pricingPosition(own,profiles);const gaps=assortmentGap(own,profiles);const currency=own.currencies?.[0]||'—';
 return <main className="shell"><Sidebar projectId={id}/><section className="workspace"><header className="pageHeader"><div><p className="eyebrow">{p.name.toUpperCase()} / PRODUCT INTELLIGENCE</p><h1>Pricing & assortment</h1><p className="muted">Compare visible pricing, category breadth and product signals across your validated competitive set</p></div><form action={captureProductIntelligence.bind(null,id)}><button className="ghost">Capture snapshot</button></form></header>
 <div className="grid"><Metric label="Price position" value={pricing.label} note={pricing.delta==null?'Need comparable prices':`${Math.abs(pricing.delta)}% ${pricing.delta>=0?'above':'below'} competitor median`}/><Metric label="Your median" value={own.priceMedian?`${currency} ${Math.round(own.priceMedian).toLocaleString()}`:'—'} note="Visible price sample"/><Metric label="Categories" value={own.categories?.length||0} note="Detected store categories"/><Metric label="Assortment gaps" value={gaps.length} note="Recurring competitor categories"/></div>
 <div className="two"><article className="panel"><p className="eyebrow">PRICE LANDSCAPE</p><h2>Validated competitor medians</h2><div className="analystList"><div><b>Your store</b><span>{own.priceMedian?`${currency} ${Math.round(own.priceMedian).toLocaleString()}`:'Price not proven'}</span></div>{comps.slice(0,8).map((c:any)=><div key={c.id}><b>{c.name||c.store_url}</b><span>{c.profile?.priceMedian?`${c.profile.currencies?.[0]||''} ${Math.round(c.profile.priceMedian).toLocaleString()}`:'Price not proven'} · {c.classification}</span></div>)}</div></article>
 <article className="panel"><p className="eyebrow">ASSORTMENT GAPS</p><h2>Categories competitors repeat</h2>{gaps.length?<div className="chipCloud">{gaps.map(g=><span className="insightChip" key={g.category}>{g.category}<small>{g.count} stores</small></span>)}</div>:<p className="muted">No recurring category gap is proven from the current profiles</p>}</article></div>
 <article className="panel"><p className="eyebrow">COMPETITOR PRODUCT SIGNALS</p><h2>What NOVA can currently observe</h2><div className="productIntelGrid">{comps.slice(0,8).map((c:any)=><div className="intelStore" key={c.id}><div><b>{c.name||c.store_url}</b><small>{c.profile?.primaryMarket||'Market unknown'} · {c.profile?.platform||'Platform unknown'}</small></div><dl><div><dt>Range</dt><dd>{range(c.profile)}</dd></div><div><dt>Categories</dt><dd>{c.profile?.categories?.length||0}</dd></div><div><dt>Product signals</dt><dd>{c.profile?.productTerms?.length||0}</dd></div></dl><p>{(c.profile?.categories||[]).slice(0,5).join(' · ')||'Categories not proven'}</p></div>)}</div></article>
 </section></main>
}
function range(p:any){if(!p?.priceMin||!p?.priceMax)return 'Not proven';return `${p.currencies?.[0]||''} ${Math.round(p.priceMin).toLocaleString()}–${Math.round(p.priceMax).toLocaleString()}`}
function Metric({label,value,note}:{label:string,value:string|number,note:string}){return <article className="metric"><span>{label}</span><strong className={String(value).length>12?'metricText':''}>{value}</strong><small>{note}</small></article>}
