import {NextResponse} from 'next/server';
import {createSupabaseServerClient} from '../../../../../lib/supabase/server';
import {askNOVA} from '../../../../../lib/ai/router';
import {buildAIContext} from '../../../../../lib/ai/context';
import {runCompetitorResearch} from '../../../../../lib/research/session';

async function projectForAI(supabase:any,id:string){const full=await supabase.from('projects').select('id,name,stores(url,profile,audit_runs(score,created_at)),competitors(id,name,store_url,profile,classification,match_score,confidence_score,status),opportunities(id,title,impact,priority,decision_score,status,evidence,recommendation),change_events(id,kind,summary,created_at),persona_reports(id,report,source_summary,provider,confidence,created_at),research_sessions(id,status,quality_score,metrics,started_at)').eq('id',id).maybeSingle();if(!full.error)return full;const base=await supabase.from('projects').select('id,name,stores(url,profile,audit_runs(score,created_at)),competitors(id,name,store_url,profile,classification,match_score,confidence_score,status),opportunities(id,title,impact,priority,decision_score,status,evidence,recommendation),change_events(id,kind,summary,created_at)').eq('id',id).maybeSingle();if(base.data){(base.data as any).persona_reports=[];(base.data as any).research_sessions=[]}return base}
function intent(q:string){const x=q.toLowerCase();if(/(?:find|discover|search|research).{0,25}(?:competitor|competitors)|(?:competitor|competitors).{0,25}(?:find|discover|search|research)/i.test(x))return 'competitor_research';if(/buyer persona|persona|customer segment|customer segments/i.test(x))return 'persona';if(/audit|scan my store|scan the store/i.test(x))return 'audit';if(/monitor|changes this week|competitor changes/i.test(x))return 'monitoring';return 'answer'}
export async function GET(_req:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const {data}=await supabase.from('ai_chat_messages').select('id,role,content,provider,confidence,evidence,page_context,created_at').eq('project_id',id).order('created_at',{ascending:false}).limit(30);return NextResponse.json({messages:[...(data||[])].reverse()},{headers:{'cache-control':'no-store'}})}
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){
 try{const {id}=await params;const body=await req.json();const question=String(body?.question||'').trim().slice(0,1600),pageContext=String(body?.pageContext||'').slice(0,240);if(!question)return NextResponse.json({error:'Ask NOVA a question first'},{status:400});const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const command=intent(question);
  if(command==='competitor_research'){
   const run=await runCompetitorResearch({projectId:id,supabase,userId:user.id,source:'chat_command'});const summaryQuestion=`Summarize the competitor research session I just ran. Explain how many candidates were found, how many passed, research quality, strongest verified competitors, and what I should do next. Do not invent any domain.`;const refreshed=await projectForAI(supabase,id);const {context,fallback}=buildAIContext(refreshed.data||{},summaryQuestion);(context as any).researchRun={sessionId:run.sessionId,quality:run.quality,candidates:run.candidates,crawled:run.crawled,accepted:run.accepted.map((x:any)=>({name:x.name,domain:x.domain,match:x.match,confidence:x.confidence})),synthesis:run.synthesis,error:run.error};const result=await askNOVA({projectName:(refreshed.data as any)?.name||'NOVA Project',question:summaryQuestion,context,fallback:{...fallback,answer:run.accepted.length?`Research completed with ${run.accepted.length} verified direct competitors from ${run.candidates} qualified candidates. Research quality is ${run.quality}/100.`:`Research completed with no verified direct competitors. NOVA did not save weak or invented domains. Research quality is ${run.quality}/100.`}});await supabase.from('ai_chat_messages').insert([{project_id:id,user_id:user.id,role:'user',content:question,page_context:pageContext||null},{project_id:id,user_id:user.id,role:'assistant',content:result.answer,provider:result.provider,confidence:result.confidence,evidence:result.evidence,page_context:pageContext||null}]);return NextResponse.json({...result,command:'competitor_research',research:run,actions:[{label:'Open competitor research',href:`/projects/${id}/competitors`}]} ,{headers:{'cache-control':'no-store'}})
  }
  const {data:p,error}=await projectForAI(supabase,id);if(error||!p)return NextResponse.json({error:'Project not found'},{status:404});const {context,fallback}=buildAIContext(p,question);(context as any).currentPage=pageContext||null;const result=await askNOVA({projectName:p.name,question,context,fallback});const actions=command==='persona'?[{label:'Open Buyer Persona',href:`/projects/${id}/persona`}]:command==='audit'?[{label:'Open Audits',href:`/projects/${id}/audits`}]:command==='monitoring'?[{label:'Open Monitoring',href:`/projects/${id}/monitoring`}]:[];await supabase.from('ai_chat_messages').insert([{project_id:id,user_id:user.id,role:'user',content:question,page_context:pageContext||null},{project_id:id,user_id:user.id,role:'assistant',content:result.answer,provider:result.provider,confidence:result.confidence,evidence:result.evidence,page_context:pageContext||null}]);return NextResponse.json({...result,command,actions},{headers:{'cache-control':'no-store'}})
 }catch(e:any){return NextResponse.json({error:'NOVA AI could not complete this request',detail:process.env.NODE_ENV==='development'?String(e?.message||e):undefined},{status:500})}
}
