'use client';
import {useState} from 'react';

type Result={provider:'gemini'|'groq'|'openrouter'|'deterministic';model:string;answer:string;confidence:number;followups:string[];evidence:string[];note?:string};
export function AIAnalyst({projectId,initial,providers}:{projectId:string;initial:Result;providers:{gemini:boolean;groq:boolean;openrouter:boolean;primary:string}}){
 const [q,setQ]=useState('');const [result,setResult]=useState<Result>(initial);const [pending,setPending]=useState(false);const [error,setError]=useState('');
 const ask=async(question?:string)=>{const text=(question??q).trim();if(!text||pending)return;setQ(text);setPending(true);setError('');try{const r=await fetch(`/api/projects/${projectId}/ai`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:text})});const j=await r.json();if(!r.ok)throw new Error(j.error||'AI request failed');setResult(j)}catch(e:any){setError(String(e?.message||e))}finally{setPending(false)}};
 return <>
  <article className="panel analystHero aiComposer"><div className="aiProviderRow"><span className={`aiStatus ${providers.gemini||providers.groq||providers.openrouter?'online':'fallback'}`}/><b>{providers.primary}</b><small>{providers.gemini?'Gemini primary':providers.groq?'Groq active':providers.openrouter?'OpenRouter Free active':'Evidence engine only'}</small></div><form className="analystAsk" onSubmit={e=>{e.preventDefault();ask()}}><input value={q} onChange={e=>setQ(e.target.value)} disabled={pending} placeholder="Ask NOVA about competitors, pricing, CRO gaps or what to do next"/><button className="primary" disabled={pending}>{pending?<><span className="miniSpinner"/>Thinking…</>:'Ask NOVA AI'}</button></form><div className="promptChips">{['What should I test first?','Who is my closest direct competitor?','Why are my competitors relevant?','Am I overpriced?','What changed this week?'].map(x=><button type="button" key={x} disabled={pending} onClick={()=>ask(x)}>{x}</button>)}</div>{pending&&<div className="aiThinking"><i/><span>Reading your NOVA evidence and comparing signals…</span></div>}{error&&<p className="errorText">{error}</p>}</article>
  <article className="panel analystAnswer aiAnswer"><div className="panelhead"><div><p className="eyebrow">GROUNDED AI ANSWER</p><h2>NOVA Analyst</h2></div><div className="aiMeta"><span className={`providerPill ${result.provider}`}>{result.provider==='deterministic'?'NOVA Engine':result.provider}</span><span className="confidenceBadge high"><b>{result.confidence}%</b><small>confidence</small></span></div></div><p className="analystLead">{result.answer}</p>{result.followups?.length>0&&<div className="promptChips followupChips">{result.followups.map(x=><button type="button" key={x} disabled={pending} onClick={()=>ask(x)}>{x}</button>)}</div>}{result.evidence?.length>0&&<div className="evidenceStack">{result.evidence.map((e,i)=><div key={i}><span>Evidence {i+1}</span><p>{e}</p></div>)}</div>}{result.note&&<p className="panelNote">{result.note}</p>}<p className="panelNote">AI is constrained to your NOVA project evidence. Missing evidence stays unknown instead of being invented.</p></article>
 </>;
}
