'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
type Msg={id?:string;role:'user'|'assistant';content:string;provider?:string;confidence?:number;evidence?:string[];actions?:{label:string;href:string}[]};
export function ChatWithNOVA({projectId}:{projectId:string}){
 const [open,setOpen]=useState(false),[messages,setMessages]=useState<Msg[]>([]),[q,setQ]=useState(''),[pending,setPending]=useState(false),[pendingMode,setPendingMode]=useState<'answer'|'research'>('answer'),[loaded,setLoaded]=useState(false),[error,setError]=useState('');const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!open||loaded)return;setLoaded(true);fetch(`/api/projects/${projectId}/ai`).then(r=>r.json()).then(j=>setMessages(j.messages||[])).catch(()=>{})},[open,loaded,projectId]);useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth'})},[messages,pending]);
 const looksLikeResearch=(text:string)=>/(?:find|discover|search|research).{0,25}(?:competitor|competitors)|(?:competitor|competitors).{0,25}(?:find|discover|search|research)/i.test(text);
 const ask=async(text?:string)=>{const question=(text??q).trim();if(!question||pending)return;setQ('');setError('');setPending(true);setPendingMode(looksLikeResearch(question)?'research':'answer');setMessages(m=>[...m,{role:'user',content:question}]);try{const r=await fetch(`/api/projects/${projectId}/ai`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question,pageContext:location.pathname})});const j=await r.json();if(!r.ok)throw new Error(j.error||'NOVA AI request failed');setMessages(m=>[...m,{role:'assistant',content:j.answer,provider:j.provider,confidence:j.confidence,evidence:j.evidence,actions:j.actions||[]}])}catch(e:any){setError(String(e?.message||e))}finally{setPending(false)}};
 return <><button className="novaChatLauncher" type="button" onClick={()=>setOpen(true)} aria-label="Chat with NOVA"><span>✦</span><b>Chat with NOVA</b></button>{open&&<div className="novaChatBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><aside className="novaChatDrawer" role="dialog" aria-label="Chat with NOVA"><header><div className="novaChatIdentity"><span>✦</span><div><b>Chat with NOVA</b><small>Project-aware AI · Command layer · Evidence grounded</small></div></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close">×</button></header><div className="novaChatContext"><i/><span>Ask questions or give commands. NOVA can research competitors and reason across audits, pricing, monitoring, opportunities and buyer personas</span></div><div className="novaChatMessages">{!messages.length&&!pending&&<div className="novaChatWelcome"><span>✦</span><h3>What do you want NOVA to do?</h3><p>Ask a decision question or launch a research workflow directly from chat</p><div>{['Find my direct competitors','What should I work on first?','What does my buyer persona tell me?','Give me 3 test ideas'].map(x=><button key={x} onClick={()=>ask(x)}>{x}</button>)}</div></div>}{messages.map((m,i)=><div key={m.id||i} className={`novaChatMessage ${m.role}`}><div className="novaChatBubble"><p>{m.content}</p>{m.role==='assistant'&&<div className="novaChatMeta"><span>{m.provider==='deterministic'?'NOVA Engine':m.provider||'NOVA AI'}</span>{m.confidence!=null&&<span>{m.confidence}% confidence</span>}</div>}{m.role==='assistant'&&m.evidence?.length?<details><summary>Evidence</summary><ul>{m.evidence.slice(0,4).map((x,j)=><li key={j}>{x}</li>)}</ul></details>:null}{m.actions?.length?<div className="novaChatActions">{m.actions.map(a=><Link key={a.href} href={a.href} onClick={()=>setOpen(false)}>{a.label}</Link>)}</div>:null}</div></div>)}{pending&&<div className="novaChatMessage assistant"><div className="novaChatBubble thinking"><i/><span>{pendingMode==='research'?'Running market research: planning → search → crawl → verify → AI review…':'Connecting the evidence…'}</span></div></div>}{error&&<p className="novaChatError">{error}</p>}<div ref={end}/></div><form className="novaChatComposer" onSubmit={e=>{e.preventDefault();ask()}}><textarea value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}}} placeholder="Ask or command NOVA…" rows={2}/><button type="submit" disabled={pending||!q.trim()}>{pending?'…':'↑'}</button><small>Try: “Find my direct competitors” · Enter to send</small></form></aside></div>}</>;
}
