import 'server-only';
import type {StoreProfile} from '../competitors/store-intelligence';
import type {Candidate} from '../competitors/discovery';
import {runNOVAWorkflowTask} from '../ai/orchestrator';
import {buildStoreFingerprint} from './fingerprint';

export type ResearchBrief={businessSummary:string;directCompetitorDefinition:string;mustMatch:string[];shouldMatch:string[];rejectIf:string[];searchConcepts:string[];productSynonyms:string[];localTerms:string[];provider?:string};
export type ResearchPlan={local:string[];product:string[];commercial:string[];arabic:string[];regional:string[];budget:number;provider?:string};

function uniq(xs:any[],max=8){return [...new Set((xs||[]).map(x=>String(x||'').replace(/\s+/g,' ').trim()).filter(x=>x.length>3))].slice(0,max)}
export async function buildResearchBrief(profile:StoreProfile):Promise<ResearchBrief>{
 const fp=buildStoreFingerprint(profile);const fallback:ResearchBrief={businessSummary:`${fp.identity.businessModel} selling ${fp.taxonomy.categories.slice(0,3).join(', ')||'e-commerce products'} in ${fp.identity.market||'an unproven market'}`,directCompetitorDefinition:`A commercial store targeting ${fp.identity.market||'the same proven market'} with overlapping products, categories and price positioning`,mustMatch:['Same primary selling market','Real e-commerce storefront','Meaningful product/category overlap'],shouldMatch:['Compatible price tier','Compatible currency','Similar audience/style positioning'],rejectIf:['Marketplace/directory rather than comparable retailer','Different proven primary market','No meaningful product overlap'],searchConcepts:uniq([...fp.taxonomy.categories,...fp.taxonomy.productTerms],8),productSynonyms:fp.taxonomy.productTerms.slice(0,6),localTerms:uniq([fp.identity.market||'',fp.identity.currency||'',...fp.audience.style],6)};
 try{const r=await runNOVAWorkflowTask<any>('research_brief',{system:'You are NOVA Market Research Strategist. Build a strict evidence-grounded research brief. Never name competitor domains. Never invent customer facts. Direct competitor means same commercial market plus overlapping products/categories and comparable buying intent. Return JSON only.',prompt:`STORE FINGERPRINT:\n${JSON.stringify(fp,null,2)}\nReturn {"businessSummary":"","directCompetitorDefinition":"","mustMatch":[],"shouldMatch":[],"rejectIf":[],"searchConcepts":[],"productSynonyms":[],"localTerms":[]}.`,maxTokens:1700});const d=r.data||{};return {...fallback,businessSummary:String(d.businessSummary||fallback.businessSummary),directCompetitorDefinition:String(d.directCompetitorDefinition||fallback.directCompetitorDefinition),mustMatch:uniq(d.mustMatch,7)||fallback.mustMatch,shouldMatch:uniq(d.shouldMatch,7)||fallback.shouldMatch,rejectIf:uniq(d.rejectIf,7)||fallback.rejectIf,searchConcepts:uniq(d.searchConcepts,10),productSynonyms:uniq(d.productSynonyms,8),localTerms:uniq(d.localTerms,8),provider:r.provider}}catch{return fallback}
}
export async function buildResearchPlan(profile:StoreProfile,brief:ResearchBrief):Promise<ResearchPlan>{
 const fp=buildStoreFingerprint(profile),market=fp.identity.market||'',currency=fp.identity.currency||'',base=brief.searchConcepts.slice(0,3).join(' ')||fp.taxonomy.categories.slice(0,2).join(' ')||fp.taxonomy.productTerms.slice(0,3).join(' '),prod=brief.productSynonyms.slice(0,3).join(' ')||base;
 const fallback:ResearchPlan={local:uniq([`${base} ${market} ${currency} online store`,`${prod} ${market} local brand`],2),product:uniq([`${prod} ${market} shop`],1),commercial:uniq([`${base} ${market} buy online brand`],1),arabic:profile.languageFamily==='Arabic'||profile.languageFamily==='Mixed'?uniq([`${prod} متجر ${market==='Egypt'?'مصر':market}`],1):[],regional:uniq([`${base} ${market||'Middle East'} brand`],1),budget:4};
 try{const r=await runNOVAWorkflowTask<any>('search_plan',{system:'You are NOVA Search Planner. Generate concise search queries only, never competitor names or domains. Prioritize the exact local country, commercial intent and specific products. Avoid generic industry queries. Return JSON only.',prompt:`STORE FINGERPRINT:\n${JSON.stringify(fp,null,2)}\nRESEARCH BRIEF:\n${JSON.stringify(brief,null,2)}\nReturn {"local":[max2],"product":[max1],"commercial":[max1],"arabic":[max1],"regional":[max1],"budget":2-5}.`,maxTokens:1400});const d=r.data||{};return {local:uniq(d.local,2).length?uniq(d.local,2):fallback.local,product:uniq(d.product,1),commercial:uniq(d.commercial,1),arabic:uniq(d.arabic,1),regional:uniq(d.regional,1),budget:Math.max(2,Math.min(5,Number(d.budget||fallback.budget))),provider:r.provider}}catch{return fallback}
}
export function prequalifyCandidates(profile:StoreProfile,candidates:Candidate[],brief:ResearchBrief){const own=buildStoreFingerprint(profile);return candidates.map(c=>{const text=`${c.title} ${c.snippet}`.toLowerCase();let score=c.preScore;const reasons:string[]=[];if(c.scope==='local'){score+=8;reasons.push('local search scope')}if(c.geoScore>=50){score+=10;reasons.push('strong geo evidence')}if(c.intentScore>=60){score+=8;reasons.push('commercial intent')}if(c.queryHits>=2){score+=7;reasons.push('multi-query agreement')}if(/marketplace|directory|magazine|news|blog|article|wiki/.test(text)){score-=35;reasons.push('non-comparable content risk')}if(own.identity.market&&c.geoScore<15&&c.source!=='tavily'){score-=25;reasons.push('weak local-market evidence')}if(c.source==='tavily'&&c.scope==='local'){score+=5;reasons.push('country-targeted live-search prior; final market proof still required from crawl')}return {...c,preScore:Math.max(0,Math.min(100,Math.round(score))),preQualificationReasons:reasons}}).filter((c:any)=>c.preScore>=56&&c.intentScore>=42).sort((a:any,b:any)=>b.preScore-a.preScore).slice(0,10)}
export function researchQualityScore(x:{marketConfidence:number;taxonomyConfidence:number;searchCandidates:number;crawled:number;accepted:number;avgAcceptedConfidence:number;providerLive:boolean}){let s=0;s+=Math.min(22,x.marketConfidence*.22);s+=Math.min(18,x.taxonomyConfidence*.18);s+=Math.min(15,x.searchCandidates*2.5);s+=Math.min(15,x.crawled*3);s+=Math.min(18,x.accepted*6);s+=Math.min(8,x.avgAcceptedConfidence*.08);s+=x.providerLive?4:0;return Math.max(0,Math.min(100,Math.round(s)))}
export async function synthesizeCompetitorSet(profile:StoreProfile,accepted:any[],rejected:any[],brief:ResearchBrief){const compact={store:buildStoreFingerprint(profile),brief,accepted:accepted.slice(0,6).map(x=>({name:x.name,domain:x.profile?.domain,classification:x.classification,match:x.match,confidence:x.confidence,signals:x.signals,pricing:x.profile?buildStoreFingerprint(x.profile).pricing:null,categories:x.profile?.categories?.slice(0,8)})),rejected:rejected.slice(0,8).map(x=>({domain:x.domain,reason:x.rejectionReasons?.slice(0,3)}))};try{const r=await runNOVAWorkflowTask<any>('competitor_synthesis',{system:'You are NOVA Competitive Intelligence Synthesizer. Use only supplied validated evidence. Never introduce a new domain. Explain the set, key market patterns, pricing/category gaps and what should not be copied. Return JSON only.',prompt:`EVIDENCE:\n${JSON.stringify(compact,null,2)}\nReturn {"summary":"","marketPatterns":[],"pricingInsights":[],"categoryInsights":[],"opportunities":[],"cautions":[]}.`,maxTokens:2200});return {provider:r.provider,...r.data}}catch{return {provider:'deterministic',summary:accepted.length?`${accepted.length} verified direct competitors passed NOVA's market and product evidence gates.`:'No verified direct competitors passed the evidence gate.',marketPatterns:[],pricingInsights:[],categoryInsights:[],opportunities:[],cautions:[]}}
}
