import 'server-only';
import {understandStore} from '../competitors/store-intelligence';
import {autoDirectAcceptance,compareStores} from '../competitors/scoring';
import {discoverCandidates} from '../competitors/discovery';
import {aiReviewCompetitorEvidence} from '../ai/competitor-discovery';
import {buildResearchBrief,buildResearchPlan,prequalifyCandidates,researchQualityScore,synthesizeCompetitorSet} from './orchestrator';
import {buildStoreFingerprint} from './fingerprint';

export async function ensureResearchStore(projectId:string,supabase:any){const {data:store}=await supabase.from('stores').select('id,url,profile').eq('project_id',projectId).limit(1).maybeSingle();if(!store)throw new Error('No connected store');let profile:any=store.profile;if(!profile||!Object.keys(profile).length||profile.primaryMarket===undefined||profile.marketConfidence===undefined){profile=await understandStore(store.url);await supabase.from('stores').update({profile,profile_updated_at:new Date().toISOString(),platform:profile.platform||undefined,currency:profile.currencies?.[0]||undefined,market:profile.marketHints?.[0]||undefined}).eq('id',store.id)}return {store,profile}}

async function validateResearchCandidate(projectId:string,supabase:any,own:any,url:string,source:string,searchOverlap:number){const candidate=await understandStore(url);if(candidate.domain===own.domain)throw new Error('Candidate is the project store');const scored=compareStores(own,candidate,searchOverlap);const gate=autoDirectAcceptance(scored,candidate,own);if(!gate.accepted)return {...scored,accepted:false,candidateProfile:candidate,rejectionReasons:[...(scored.rejectionReasons||[]),...gate.reasons]};const aiReview=await aiReviewCompetitorEvidence(own,candidate,scored);if(aiReview?.verdict==='reject'&&aiReview.confidence>=80)return {...scored,accepted:false,candidateProfile:candidate,aiReview,rejectionReasons:[...(scored.rejectionReasons||[]),`AI second-pass veto (${aiReview.confidence}%): ${aiReview.reason}`]};const row={project_id:projectId,store_url:candidate.url,normalized_url:`https://${candidate.domain}`,name:candidate.title||candidate.domain,classification:scored.classification,match_score:scored.match,confidence_score:scored.confidence,signals:scored.signals,profile:candidate,source,evidence:[...scored.evidence,'Automatic direct-competitor gate: passed',...(aiReview?[`AI second-pass ${aiReview.verdict} (${aiReview.confidence}% via ${aiReview.provider}): ${aiReview.reason}`]:[])],status:'validated',validated_at:new Date().toISOString()};const {data:saved,error}=await supabase.from('competitors').upsert(row,{onConflict:'project_id,normalized_url'}).select('id').maybeSingle();if(error)throw error;try{await supabase.from('competitor_knowledge').upsert({project_id:projectId,domain:candidate.domain,normalized_url:`https://${candidate.domain}`,profile:candidate,fingerprint:buildStoreFingerprint(candidate),confidence:scored.confidence,validation_count:1,last_verdict:'direct',last_seen_at:new Date().toISOString()},{onConflict:'project_id,domain'})}catch{}return {...scored,accepted:true,candidateProfile:candidate,aiReview,competitorId:(saved as any)?.id}}

export async function runCompetitorResearch({projectId,supabase,userId,source='competitor_discovery'}:{projectId:string;supabase:any;userId?:string|null;source?:string}){
 const {profile}=await ensureResearchStore(projectId,supabase);const brief=await buildResearchBrief(profile);const plan=await buildResearchPlan(profile,brief);
 const {data:session,error:sessionError}=await supabase.from('research_sessions').insert({project_id:projectId,created_by:userId||null,status:'running',source,research_brief:brief,search_plan:plan,provider_chain:[brief.provider,plan.provider,process.env.TAVILY_API_KEY?'tavily':'free-search-fallback'].filter(Boolean)}).select('id').maybeSingle();if(sessionError)throw sessionError;const sessionId=(session as any)?.id;
 await supabase.from('competitors').delete().eq('project_id',projectId).neq('source','manual');
 const cache={get:async(key:string)=>{const {data}=await supabase.from('discovery_search_cache').select('results,expires_at').eq('cache_key',`${projectId}:${key}`).gt('expires_at',new Date().toISOString()).maybeSingle();return Array.isArray((data as any)?.results)?(data as any).results:null},getStale:async(key:string)=>{const {data}=await supabase.from('discovery_search_cache').select('results').eq('cache_key',`${projectId}:${key}`).order('updated_at',{ascending:false}).limit(1).maybeSingle();return Array.isArray((data as any)?.results)?(data as any).results:null},set:async(key:string,rows:any[],ttlHours:number)=>{await supabase.from('discovery_search_cache').upsert({cache_key:`${projectId}:${key}`,project_id:projectId,results:rows,updated_at:new Date().toISOString(),expires_at:new Date(Date.now()+ttlHours*3600_000).toISOString()},{onConflict:'cache_key'})}};
 let raw:any[]=[];try{raw=await discoverCandidates(profile,cache,plan)}catch{}
 const {data:known}=await supabase.from('competitor_knowledge').select('domain,normalized_url,confidence,last_verdict').eq('project_id',projectId).order('last_seen_at',{ascending:false}).limit(12);const knowledge=(known||[]).filter((x:any)=>x.last_verdict==='direct'||x.last_verdict==='manual').map((x:any,i:number)=>({url:x.normalized_url,title:x.domain,snippet:'Previously validated by NOVA',source:'knowledge',rank:900+i,scope:'local',queryHits:2,geoScore:70,intentScore:70,preScore:Math.max(72,Number(x.confidence||72))}));const byDomain=new Map<string,any>();for(const c of [...raw,...knowledge]){try{const d=new URL(c.url).hostname.replace(/^www\./,'');if(d===profile.domain)continue;const prev=byDomain.get(d);if(!prev||c.preScore>prev.preScore)byDomain.set(d,c)}catch{}}
 const {data:feedback}=await supabase.from('competitor_feedback').select('domain,verdict').eq('project_id',projectId);const blocked=new Set((feedback||[]).filter((x:any)=>x.verdict==='not_competitor').map((x:any)=>String(x.domain).toLowerCase()));const referenceOnly=new Set((feedback||[]).filter((x:any)=>x.verdict==='reference_only').map((x:any)=>String(x.domain).toLowerCase()));const candidates=prequalifyCandidates(profile,[...byDomain.values()],brief).filter((c:any)=>{try{const d=new URL(c.url).hostname.replace(/^www\./,'').toLowerCase();return !blocked.has(d)&&!referenceOnly.has(d)}catch{return false}}),accepted:any[]=[],rejected:any[]=[];let crawled=0;
 for(const c of candidates.slice(0,8)){let result:any;try{crawled++;const overlap=Math.min(1,Math.max(.08,(c.preScore/100)*.58+Math.min(.28,c.queryHits*.08)));result=await validateResearchCandidate(projectId,supabase,profile,c.url,`auto:${c.source}:${c.scope}:q${c.queryHits}:pre${c.preScore}`,overlap)}catch(e:any){result={accepted:false,rejectionReasons:[String(e?.message||'Candidate crawl failed')]}}const domain=(()=>{try{return new URL(c.url).hostname.replace(/^www\./,'')}catch{return c.url}})();const row={research_session_id:sessionId,project_id:projectId,domain,url:c.url,title:c.title,source:c.source,scope:c.scope,discovery_score:c.preScore,deterministic_score:Number(result?.match||0),confidence:Number(result?.confidence||0),classification:result?.classification||null,decision:result?.accepted?'accepted':result?.classification==='Needs Verification'?'needs_verification':'rejected',rejection_reasons:result?.rejectionReasons||[],evidence:[...(result?.evidence||[]),...(c.preQualificationReasons||[])],profile:result?.candidateProfile||null,ai_review:result?.aiReview||null};await supabase.from('research_candidates').insert(row);if(result?.accepted)accepted.push({...result,name:result.candidateProfile?.title||domain,domain});else rejected.push({...row,rejectionReasons:row.rejection_reasons})}
 const avg=accepted.length?Math.round(accepted.reduce((n,x)=>n+Number(x.confidence||0),0)/accepted.length):0,quality=researchQualityScore({marketConfidence:Number(profile.marketConfidence||0),taxonomyConfidence:Number(profile.taxonomyConfidence||0),searchCandidates:candidates.length,crawled,accepted:accepted.length,avgAcceptedConfidence:avg,providerLive:Boolean(process.env.TAVILY_API_KEY)}),synthesis=await synthesizeCompetitorSet(profile,accepted,rejected,brief);const status=accepted.length?'completed':candidates.length?'partial':'failed',error=accepted.length?null:(candidates.length?'No candidate passed the strict direct gate':'Live search and project knowledge produced no qualified candidates');await supabase.from('research_sessions').update({status,metrics:{searchCandidates:candidates.length,crawled,accepted:accepted.length,rejected:rejected.length,averageAcceptedConfidence:avg,synthesis},quality_score:quality,completed_at:new Date().toISOString(),error}).eq('id',sessionId);
 return {sessionId,status,quality,brief,plan,accepted,rejected,candidates:candidates.length,crawled,synthesis,error};
}
