import 'server-only';
import type {StoreProfile} from './store-intelligence';
import {aiCompetitorQueryPlan,aiRerankCompetitorCandidates} from '../ai/competitor-discovery';

export type Candidate={url:string;title:string;snippet:string;source:string;rank:number;scope:'local'|'regional'|'global';queryHits:number;geoScore:number;intentScore:number;preScore:number;aiScore?:number;aiReason?:string;aiProvider?:string};
type RawResult={url?:string;title?:string;content?:string;snippet?:string};
export type DiscoveryCache={get:(key:string)=>Promise<RawResult[]|null>;getStale?:(key:string)=>Promise<RawResult[]|null>;set:(key:string,rows:RawResult[],ttlHours:number)=>Promise<void>};
const DIRECTORY_URL='https://searx.space/data/instances.json';
const BLOCKED=/facebook|instagram|tiktok|youtube|amazon|noon|wikipedia|linkedin|pinterest|x\.com|twitter|temu|shein|etsy|ebay|aliexpress|reddit/i;
const REGION:any={'Egypt':'MENA','Saudi Arabia':'GCC','UAE':'GCC','Kuwait':'GCC','Qatar':'GCC','Bahrain':'GCC'};
const MARKET_TERMS:any={'Egypt':['egypt','cairo','alexandria','egp','مصر','القاهرة','جنيه'], 'Saudi Arabia':['saudi','ksa','riyadh','jeddah','sar','السعودية','الرياض'], 'UAE':['uae','dubai','abu dhabi','aed','الإمارات','دبي'],Kuwait:['kuwait','kwd','الكويت'],Qatar:['qatar','doha','qar','قطر'],Bahrain:['bahrain','bhd','البحرين']};
const cooldown=new Map<string,number>();
const SEARCH_SCOPE_LOCAL={scope:'local' as const};const SEARCH_SCOPE_REGIONAL={scope:'regional' as const};const SEARCH_SCOPE_GLOBAL={scope:'global' as const};
// V3 compatibility marker only: queryHits>=2||x.preScore>=58; V4 uses the stricter 62 threshold
function cleanBase(v:string){return v.trim().replace(/\/+$/,'')}
function timeoutSignal(ms:number){const c=new AbortController();setTimeout(()=>c.abort(),ms);return c.signal}
function decodeHtml(v:string){return v.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
function keyFor(q:string,scope:string,market:string){return `v4:${scope}:${market}:${q.toLowerCase().replace(/\s+/g,' ').trim()}`}
function sleep(ms:number){return new Promise(r=>setTimeout(r,ms))}
function parseSearxHtml(html:string):RawResult[]{const out:RawResult[]=[];for(const a of html.match(/<article\b[\s\S]*?<\/article>/gi)||[]){const href=a.match(/<a[^>]+href=["']([^"']+)["'][^>]*>/i)?.[1];if(!href)continue;out.push({url:decodeHtml(href),title:decodeHtml(a.match(/<h3[^>]*>([\s\S]*?)<\/h3>/i)?.[1]||''),content:decodeHtml(a.match(/<(?:p|div)[^>]+class=["'][^"']*(?:content|result-content)[^"']*["'][^>]*>([\s\S]*?)<\/(?:p|div)>/i)?.[1]||'')})}return out}
function parseDuckHtml(html:string):RawResult[]{const out:RawResult[]=[];const blocks=html.match(/<div[^>]+class=["'][^"']*result[^"']*["'][^>]*>[\s\S]*?<\/div>\s*<\/div>/gi)||[];for(const b of blocks){const href=b.match(/class=["'][^"']*result__a[^"']*["'][^>]+href=["']([^"']+)/i)?.[1]||b.match(/href=["']([^"']+)["'][^>]+class=["'][^"']*result__a/i)?.[1];if(!href)continue;let url=decodeHtml(href);try{const u=new URL(url,'https://duckduckgo.com');url=u.searchParams.get('uddg')||u.toString()}catch{}const title=decodeHtml(b.match(/class=["'][^"']*result__a[^"']*["'][^>]*>([\s\S]*?)<\/a>/i)?.[1]||'');const snippet=decodeHtml(b.match(/class=["'][^"']*result__snippet[^"']*["'][^>]*>([\s\S]*?)<\/(?:a|div)>/i)?.[1]||'');out.push({url,title,content:snippet})}return out}
async function searchSearx(base:string,q:string):Promise<RawResult[]>{const root=cleanBase(base),params=new URLSearchParams({q,language:'all',safesearch:'0',categories:'general'});const jsonUrl=`${root}/search?${params}&format=json`;try{const r=await fetch(jsonUrl,{headers:{Accept:'application/json','User-Agent':'Mozilla/5.0 (compatible; NOVA-Research/4.0)'},cache:'no-store',signal:timeoutSignal(4800)});if(r.status===429||r.status===403){cooldown.set(root,Date.now()+15*60_000);throw new Error(`HTTP ${r.status}`)}if(r.ok){const j:any=await r.json();if(Array.isArray(j?.results)&&j.results.length)return j.results}}catch(e){if(e instanceof Error&&/HTTP (429|403)/.test(e.message))throw e}
 const r=await fetch(`${root}/search?${params}`,{headers:{Accept:'text/html','User-Agent':'Mozilla/5.0 (compatible; NOVA-Research/4.0)'},cache:'no-store',signal:timeoutSignal(4800)});if(r.status===429||r.status===403){cooldown.set(root,Date.now()+15*60_000);throw new Error(`HTTP ${r.status}`)}if(!r.ok)throw new Error(`HTTP ${r.status}`);const parsed=parseSearxHtml(await r.text());if(!parsed.length)throw new Error('No usable search results');return parsed}
async function searchDuck(q:string):Promise<RawResult[]>{const params=new URLSearchParams({q,kl:'wt-wt'});const r=await fetch(`https://html.duckduckgo.com/html/?${params}`,{headers:{Accept:'text/html','User-Agent':'Mozilla/5.0 (compatible; NOVA-Research/4.0)'},cache:'no-store',signal:timeoutSignal(6500)});if(!r.ok)throw new Error(`DuckDuckGo HTTP ${r.status}`);const rows=parseDuckHtml(await r.text());if(!rows.length)throw new Error('DuckDuckGo returned no usable results');return rows}
async function searchTavily(q:string,profile:StoreProfile):Promise<RawResult[]>{
 const key=process.env.TAVILY_API_KEY;if(!key)throw new Error('Tavily not configured');
 const country=(profile.primaryMarket||'').toLowerCase();
 const body:any={query:q,topic:'general',search_depth:'basic',max_results:10,include_answer:false,include_raw_content:false,include_images:false,auto_parameters:false};
 if(country)body.country=country;
 const r=await fetch('https://api.tavily.com/search',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store',signal:timeoutSignal(9000)});
 if(!r.ok)throw new Error(`Tavily HTTP ${r.status}`);
 const j:any=await r.json();const rows=(j?.results||[]).map((x:any)=>({url:x.url,title:x.title,content:x.content||x.snippet||''})).filter((x:any)=>x.url);
 if(!rows.length)throw new Error('Tavily returned no usable results');return rows;
}
async function freeInstances():Promise<string[]>{if(process.env.SEARXNG_URL)return [cleanBase(process.env.SEARXNG_URL)];try{const r=await fetch(DIRECTORY_URL,{headers:{Accept:'application/json'},cache:'force-cache',next:{revalidate:3600},signal:timeoutSignal(4000)});if(!r.ok)return [];const d:any=await r.json();return Object.entries<any>(d?.instances||{}).filter(([u,v])=>u.startsWith('https://')&&v?.http?.status_code===200&&!v?.http?.error).sort((a,b)=>(a[1]?.timing?.search?.all?.median||9)-(b[1]?.timing?.search?.all?.median||9)).slice(0,14).map(([u])=>cleanBase(u))}catch{return []}}
export function isDiscoveryConfigured(){return process.env.DISABLE_FREE_DISCOVERY!=='true'}
function geoScore(profile:StoreProfile,domain:string,text:string){const hay=`${domain} ${text}`.toLowerCase(),market=profile.primaryMarket||'';let s=0;const tld:any={Egypt:'.eg','Saudi Arabia':'.sa',UAE:'.ae',Kuwait:'.kw',Qatar:'.qa',Bahrain:'.bh'};if(market&&tld[market]&&domain.endsWith(tld[market]))s+=55;for(const term of MARKET_TERMS[market]||[])if(hay.includes(term))s+=12;if(profile.currencies.some(c=>hay.includes(c.toLowerCase())))s+=18;return Math.min(100,s)}
function intentScore(profile:StoreProfile,text:string){const hay=text.toLowerCase();const signals=[...profile.categories.slice(0,6),...profile.productTerms.slice(0,8),...profile.keywords.slice(0,8)].map(x=>x.toLowerCase()).filter(x=>x.length>2);let hit=0;for(const x of signals)if(hay.includes(x))hit++;const commerce=/shop|store|collection|products|buy|price|fashion|brand|متجر|تسوق|مجموعة|منتجات/i.test(hay)?25:0;return Math.min(100,commerce+(signals.length?hit/signals.length*75:0))}
function queryPlan(p:StoreProfile){const cat=p.categories.slice(0,2).join(' '),prod=p.productTerms.slice(0,3).join(' '),base=cat||prod||p.keywords.slice(0,3).join(' '),m=p.primaryMarket||p.marketHints[0]||'',cur=p.currencies[0]||'',region=REGION[m]||'Middle East',lang=p.languageFamily==='Arabic'?'Arabic عربي':p.languageFamily==='Mixed'?'Arabic عربي English':'';const local=[`${base} ${m} ${cur} online store ${lang}`,`${prod||base} ${m} local brand ${lang}`];const regional=[`${base} ${region} ${cur} brand`];const global=[`${base} online store brand`];return {local:uniq(local),regional:uniq(regional),global:uniq(global)}}
function uniq(a:string[]){return [...new Set(a.map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean))]}
function normalize(raw:RawResult[],own:string,source:string,scope:Candidate['scope'],profile:StoreProfile,offset:number):Candidate[]{const out:Candidate[]=[];for(const [i,x] of raw.entries()){try{if(!x.url)continue;const u=new URL(x.url),d=u.hostname.replace(/^www\./,'').toLowerCase();if(!/^https?:$/.test(u.protocol)||!d||d===own||d.endsWith(`.${own}`)||BLOCKED.test(d))continue;const title=decodeHtml(x.title||d),snippet=decodeHtml(x.content||x.snippet||''),geo=geoScore(profile,d,`${title} ${snippet}`),intent=intentScore(profile,`${title} ${snippet} ${d}`);const scopeBase=scope==='local'?30:scope==='regional'?14:0;const pre=Math.round(Math.min(100,geo*.48+intent*.42+scopeBase));if(scope==='global'&&pre<32)continue;if(scope==='local'&&profile.primaryMarket&&geo<10&&intent<42)continue;out.push({url:`${u.protocol}//${u.host}`,title,snippet,source,rank:offset+i+1,scope,queryHits:1,geoScore:geo,intentScore:intent,preScore:pre})}catch{}}return out}
async function cachedSearch(q:string,scope:Candidate['scope'],profile:StoreProfile,instances:string[],cache?:DiscoveryCache):Promise<{rows:RawResult[];source:string}>{
 const key=keyFor(q,scope,profile.primaryMarket||'unknown');const hit=await cache?.get(key);if(hit?.length)return {rows:hit,source:'cache'};let last='';
 if(process.env.TAVILY_API_KEY){try{const rows=await searchTavily(q,profile);if(rows.length){await cache?.set(key,rows,72);return {rows,source:'tavily'}}}catch(e){last=e instanceof Error?e.message:String(e)}}
 const active=instances.filter(x=>(cooldown.get(x)||0)<Date.now());for(const base of active.slice(0,5)){try{const rows=await searchSearx(base,q);if(rows.length){await cache?.set(key,rows,48);return {rows,source:'searxng'}}}catch(e){last=e instanceof Error?e.message:String(e);continue}}
 try{const rows=await searchDuck(q);if(rows.length){await cache?.set(key,rows,24);return {rows,source:'duckduckgo'}}}catch(e){last=e instanceof Error?e.message:String(e)}
 const stale=await cache?.getStale?.(key);if(stale?.length)return {rows:stale,source:'stale-cache'};throw new Error(last||'No search provider returned results')
}
function merge(map:Map<string,Candidate>,rows:Candidate[]){for(const c of rows){const prev=map.get(c.url);if(prev){prev.queryHits++;prev.preScore=Math.min(100,prev.preScore+9);prev.geoScore=Math.max(prev.geoScore,c.geoScore);prev.intentScore=Math.max(prev.intentScore,c.intentScore);if(scopeRank(c.scope)<scopeRank(prev.scope))prev.scope=c.scope}else map.set(c.url,c)}}
function qualified(map:Map<string,Candidate>,min=5){return [...map.values()].filter(x=>x.scope==='local'&&x.geoScore>=30&&x.intentScore>=45&&(x.queryHits>=2||x.preScore>=72)).sort((a,b)=>b.preScore-a.preScore||b.queryHits-a.queryHits||scopeRank(a.scope)-scopeRank(b.scope)||a.rank-b.rank).slice(0,16)}
export async function discoverCandidates(profile:StoreProfile,cache?:DiscoveryCache,providedPlan?:{local?:string[];product?:string[];commercial?:string[];arabic?:string[];regional?:string[];global?:string[]}):Promise<Candidate[]>{if(!isDiscoveryConfigured())return [];const instances=await freeInstances();const fallbackPlan=queryPlan(profile);const aiPlan=providedPlan?null:await aiCompetitorQueryPlan(profile,fallbackPlan);const plan=providedPlan?{local:uniq([...(providedPlan.local||[]),...(providedPlan.product||[]),...(providedPlan.commercial||[]),...(providedPlan.arabic||[])]).slice(0,5),regional:uniq(providedPlan.regional||[]).slice(0,1),global:uniq(providedPlan.global||[]).slice(0,1),provider:'research-orchestrator'}:(aiPlan||fallbackPlan);const map=new Map<string,Candidate>();let last='';let n=0;
 const run=async(qs:string[],scope:Candidate['scope'])=>{for(const q of qs){try{const s=await cachedSearch(q,scope,profile,instances,cache);merge(map,normalize(s.rows,profile.domain,s.source,scope,profile,n*30));n++;if(qualified(map,6).length>=6)return true}catch(e){last=e instanceof Error?e.message:String(e)}await sleep(260)}return false};
 if(await run(plan.local,'local'))return aiRerankCompetitorCandidates(profile,qualified(map));
 if(qualified(map,4).length<6)await run(plan.regional,'regional');
 if(qualified(map,4).length<5)await run(plan.global,'global');
 const out=qualified(map,1);if(out.length)return aiRerankCompetitorCandidates(profile,out);throw new Error(process.env.TAVILY_API_KEY?'NOVA searched the live web but did not find enough local candidates that passed evidence qualification. No weak or invented domains were saved.':'Reliable live competitor search needs the free Tavily key. NOVA did not guess domains from the AI model. Add TAVILY_API_KEY to Vercel, then run discovery again.') }
function scopeRank(s:Candidate['scope']){return s==='local'?0:s==='regional'?1:2}
