import 'server-only';
import type {StoreProfile} from './store-intelligence';
export type Candidate={url:string;title:string;snippet:string;source:string;rank:number;scope:'local'|'regional'|'global';queryHits:number;geoScore:number;intentScore:number;preScore:number};
type RawResult={url?:string;title?:string;content?:string;snippet?:string};
const DIRECTORY_URL='https://searx.space/data/instances.json';
const BLOCKED=/facebook|instagram|tiktok|youtube|amazon|noon|wikipedia|linkedin|pinterest|x\.com|twitter|temu|shein|etsy|ebay|aliexpress|reddit/i;
const REGION:any={'Egypt':'MENA','Saudi Arabia':'GCC','UAE':'GCC','Kuwait':'GCC','Qatar':'GCC','Bahrain':'GCC'};
const MARKET_TERMS:any={'Egypt':['egypt','cairo','alexandria','egp','مصر','القاهرة','جنيه'], 'Saudi Arabia':['saudi','ksa','riyadh','jeddah','sar','السعودية','الرياض'], 'UAE':['uae','dubai','abu dhabi','aed','الإمارات','دبي'],Kuwait:['kuwait','kwd','الكويت'],Qatar:['qatar','doha','qar','قطر'],Bahrain:['bahrain','bhd','البحرين']};
function cleanBase(v:string){return v.trim().replace(/\/+$/,'')}function timeoutSignal(ms:number){const c=new AbortController();setTimeout(()=>c.abort(),ms);return c.signal}function decodeHtml(v:string){return v.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
function parseSearxHtml(html:string):RawResult[]{const out:RawResult[]=[];for(const a of html.match(/<article\b[\s\S]*?<\/article>/gi)||[]){const href=a.match(/<a[^>]+href=["']([^"']+)["'][^>]*>/i)?.[1];if(!href)continue;out.push({url:decodeHtml(href),title:decodeHtml(a.match(/<h3[^>]*>([\s\S]*?)<\/h3>/i)?.[1]||''),content:decodeHtml(a.match(/<(?:p|div)[^>]+class=["'][^"']*(?:content|result-content)[^"']*["'][^>]*>([\s\S]*?)<\/(?:p|div)>/i)?.[1]||'')})}return out}
async function searchInstance(base:string,q:string):Promise<RawResult[]>{const root=cleanBase(base),params=new URLSearchParams({q,language:'all',safesearch:'0',categories:'general'});try{const r=await fetch(`${root}/search?${params}&format=json`,{headers:{Accept:'application/json','User-Agent':'NOVA-Research/2.0'},cache:'no-store',signal:timeoutSignal(5000)});if(r.ok){const j:any=await r.json();if(Array.isArray(j?.results)&&j.results.length)return j.results}}catch{}const r=await fetch(`${root}/search?${params}`,{headers:{Accept:'text/html','User-Agent':'Mozilla/5.0 NOVA-Research/2.0'},cache:'no-store',signal:timeoutSignal(5000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const parsed=parseSearxHtml(await r.text());if(!parsed.length)throw new Error('No usable search results');return parsed}
async function freeInstances():Promise<string[]>{if(process.env.SEARXNG_URL)return [cleanBase(process.env.SEARXNG_URL)];try{const r=await fetch(DIRECTORY_URL,{headers:{Accept:'application/json'},cache:'no-store',signal:timeoutSignal(4000)});if(!r.ok)return [];const d:any=await r.json();return Object.entries<any>(d?.instances||{}).filter(([u,v])=>u.startsWith('https://')&&v?.http?.status_code===200&&!v?.http?.error).sort((a,b)=>(a[1]?.timing?.search?.all?.median||9)-(b[1]?.timing?.search?.all?.median||9)).slice(0,10).map(([u])=>cleanBase(u))}catch{return []}}
export function isDiscoveryConfigured(){return process.env.DISABLE_FREE_DISCOVERY!=='true'}
function geoScore(profile:StoreProfile,domain:string,text:string){const hay=`${domain} ${text}`.toLowerCase(),market=profile.primaryMarket||'';let s=0;const tld:any={Egypt:'.eg','Saudi Arabia':'.sa',UAE:'.ae',Kuwait:'.kw',Qatar:'.qa',Bahrain:'.bh'};if(market&&tld[market]&&domain.endsWith(tld[market]))s+=55;for(const term of MARKET_TERMS[market]||[])if(hay.includes(term))s+=12;if(profile.currencies.some(c=>hay.includes(c.toLowerCase())))s+=18;return Math.min(100,s)}
function intentScore(profile:StoreProfile,text:string){const hay=text.toLowerCase();const signals=[...profile.categories.slice(0,6),...profile.productTerms.slice(0,8),...profile.keywords.slice(0,8)].map(x=>x.toLowerCase()).filter(x=>x.length>2);let hit=0;for(const x of signals)if(hay.includes(x))hit++;const commerce=/shop|store|collection|products|buy|price|fashion|brand|متجر|تسوق|مجموعة|منتجات/i.test(hay)?25:0;return Math.min(100,commerce+(signals.length?hit/signals.length*75:0))}
function queries(p:StoreProfile){const cat=p.categories.slice(0,3).join(' '),prod=p.productTerms.slice(0,4).join(' '),base=cat||prod||p.keywords.slice(0,4).join(' '),m=p.primaryMarket||p.marketHints[0]||'',cur=p.currencies[0]||'',lang=p.languageFamily==='Arabic'?'Arabic عربي':p.languageFamily==='Mixed'?'Arabic English':'';const region=REGION[m]||'Middle East';const qs=[{q:`${base} ${m} ${cur} online store`,scope:'local' as const},{q:`${prod||base} ${m} local brand`,scope:'local' as const},{q:`${cat||base} ${m} shop ${lang}`,scope:'local' as const},{q:`${base} ${region} ${cur} brand`,scope:'regional' as const},{q:`${base} ${region} online store`,scope:'regional' as const},{q:`${base} online store brand`,scope:'global' as const}];return qs.map(x=>({...x,q:x.q.replace(/\s+/g,' ').trim()})).filter((x,i,a)=>x.q&&a.findIndex(y=>y.q===x.q)===i)}
function normalize(raw:RawResult[],own:string,source:string,scope:Candidate['scope'],profile:StoreProfile,offset:number):Candidate[]{const out:Candidate[]=[];for(const [i,x] of raw.entries()){try{if(!x.url)continue;const u=new URL(x.url),d=u.hostname.replace(/^www\./,'').toLowerCase();if(!/^https?:$/.test(u.protocol)||!d||d===own||d.endsWith(`.${own}`)||BLOCKED.test(d))continue;const title=decodeHtml(x.title||d),snippet=decodeHtml(x.content||x.snippet||''),geo=geoScore(profile,d,`${title} ${snippet}`),intent=intentScore(profile,`${title} ${snippet} ${d}`);const scopeBase=scope==='local'?30:scope==='regional'?14:0;const pre=Math.round(Math.min(100,geo*.48+intent*.42+scopeBase));if(scope==='global'&&pre<28)continue;if(scope==='local'&&profile.primaryMarket&&geo<10&&intent<38)continue;out.push({url:`${u.protocol}//${u.host}`,title,snippet,source,rank:offset+i+1,scope,queryHits:1,geoScore:geo,intentScore:intent,preScore:pre})}catch{}}return out}
export async function discoverCandidates(profile:StoreProfile):Promise<Candidate[]>{if(!isDiscoveryConfigured())return [];const instances=await freeInstances();if(!instances.length)throw new Error('Free competitor search is temporarily unavailable. Manual validation still works');const qs=queries(profile);let last='';for(const base of instances.slice(0,6)){try{const map=new Map<string,Candidate>();for(const [qi,item] of qs.entries()){const rows=normalize(await searchInstance(base,item.q),profile.domain,'searxng',item.scope,profile,qi*30);for(const c of rows){const prev=map.get(c.url);if(prev){prev.queryHits++;prev.preScore=Math.min(100,prev.preScore+8);prev.geoScore=Math.max(prev.geoScore,c.geoScore);prev.intentScore=Math.max(prev.intentScore,c.intentScore);if(scopeRank(c.scope)<scopeRank(prev.scope))prev.scope=c.scope}else map.set(c.url,c)}}const unique=[...map.values()].filter(x=>x.queryHits>=2||x.preScore>=58).sort((a,b)=>b.preScore-a.preScore||b.queryHits-a.queryHits||scopeRank(a.scope)-scopeRank(b.scope)||a.rank-b.rank).slice(0,16);if(unique.length)return unique}catch(e){last=e instanceof Error?e.message:String(e)}}throw new Error(`Free competitor search is temporarily unavailable${last?`: ${last}`:''}. Manual validation still works`)}
function scopeRank(s:Candidate['scope']){return s==='local'?0:s==='regional'?1:2}
