import type {StoreProfile} from './store-intelligence';
export const WEIGHTS={marketOverlap:.25,categoryOverlap:.20,priceSimilarity:.15,languageMatch:.10,currencyMatch:.10,productSimilarity:.10,searchOverlap:.05,audienceSimilarity:.05};
const set=(xs:string[])=>new Set((xs||[]).map(x=>x.toLowerCase().trim()).filter(Boolean));
function jaccard(a:string[],b:string[]){const A=set(a),B=set(b);if(!A.size||!B.size)return null;let hit=0;for(const x of A)if(B.has(x))hit++;return hit/(A.size+B.size-hit)}
function fuzzyOverlap(a:string[],b:string[]){if(!a?.length||!b?.length)return null;const A=a.map(x=>x.toLowerCase()),B=b.map(x=>x.toLowerCase());let hits=0;for(const x of A)if(B.some(y=>x===y||x.includes(y)||y.includes(x)))hits++;return Math.min(1,hits/Math.max(1,Math.min(A.length,B.length)))}
function price(a:StoreProfile,b:StoreProfile){if(!a.priceMedian||!b.priceMedian)return null;const r=Math.min(a.priceMedian,b.priceMedian)/Math.max(a.priceMedian,b.priceMedian);return Math.max(0,Math.min(1,r))}
function currency(a:StoreProfile,b:StoreProfile){if(!a.currencies?.length||!b.currencies?.length)return null;return a.currencies.some(x=>b.currencies.includes(x))?1:0}
function language(a:StoreProfile,b:StoreProfile){if(!a.languageFamily||!b.languageFamily||a.languageFamily==='Unknown'||b.languageFamily==='Unknown')return null;if(a.languageFamily===b.languageFamily)return 1;if(a.languageFamily==='Mixed'||b.languageFamily==='Mixed')return .7;return .15}
function market(a:StoreProfile,b:StoreProfile){if(a.primaryMarket&&b.primaryMarket)return a.primaryMarket===b.primaryMarket?1:.05;const ah=set(a.marketHints),bh=set(b.marketHints);if(ah.size&&bh.size)return [...ah].some(x=>bh.has(x))?.9:.1;return currency(a,b)}
export function compareStores(a:StoreProfile,b:StoreProfile,searchOverlap:number|null=null){const signals={marketOverlap:market(a,b),categoryOverlap:fuzzyOverlap(a.categories.length?a.categories:a.keywords,b.categories.length?b.categories:b.keywords),priceSimilarity:price(a,b),languageMatch:language(a,b),currencyMatch:currency(a,b),productSimilarity:fuzzyOverlap(a.productTerms.length?a.productTerms:a.keywords,b.productTerms.length?b.productTerms:b.keywords),searchOverlap,audienceSimilarity:jaccard(a.keywords.slice(0,18),b.keywords.slice(0,18))};let available=0,earned=0,total=0;for(const [k,w] of Object.entries(WEIGHTS)){total+=w;const v=(signals as any)[k];if(v!=null){available+=w;earned+=Math.max(0,Math.min(1,v))*w}}let match=available?Math.round(earned/available*100):0;const confidence=Math.round(available/total*100);
 const sameMarket=signals.marketOverlap!=null&&signals.marketOverlap>=.8;const differentKnownMarket=signals.marketOverlap!=null&&signals.marketOverlap<=.15;const currencyConflict=signals.currencyMatch===0; if(differentKnownMarket)match=Math.min(match,64);if(differentKnownMarket&&currencyConflict)match=Math.min(match,55);
 let classification:string;if(sameMarket&&match>=80)classification='Local Direct';else if(sameMarket&&match>=67)classification='Local Strong';else if(!sameMarket&&match>=70)classification='Regional Strong';else if(match>=50)classification='Adjacent';else classification='Global Reference';
 const confidenceLabel=confidence>=80?'High':confidence>=55?'Medium':'Low';const evidence=Object.entries(signals).filter(([,v])=>v!=null).map(([k,v])=>`${k}: ${Math.round(Number(v)*100)}%`);if(a.primaryMarket&&b.primaryMarket)evidence.unshift(a.primaryMarket===b.primaryMarket?`Same primary market: ${a.primaryMarket}`:`Different primary markets: ${a.primaryMarket} vs ${b.primaryMarket}`);return {signals,match,confidence,classification,confidenceLabel,evidence,sameMarket}}
