import 'server-only';
import dns from 'node:dns/promises';
import net from 'node:net';

export type ProductSample={name:string;price:number|null;currency:string|null};
export type StoreProfile={
 url:string; domain:string; title:string|null; description:string|null; language:string|null; platform:string|null;
 currencies:string[]; priceMin:number|null; priceMax:number|null; priceMedian:number|null;
 keywords:string[]; categories:string[]; productTerms:string[]; productSamples:ProductSample[];
 marketHints:string[]; primaryMarket:string|null; marketConfidence:number; marketEvidence:string[];
 shippingMarkets:string[]; addressSignals:string[]; languageFamily:'Arabic'|'English'|'Mixed'|'Other'|'Unknown';
 evidence:string[];
};
const PRIVATE=[/^10\./,/^127\./,/^169\.254\./,/^192\.168\./,/^172\.(1[6-9]|2\d|3[01])\./,/^0\./];
function isPrivate(ip:string){if(net.isIPv4(ip))return PRIVATE.some(r=>r.test(ip));if(net.isIPv6(ip))return ip==='::1'||ip.startsWith('fc')||ip.startsWith('fd')||ip.startsWith('fe80:');return true}
async function publicUrl(raw:string){const u=new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`);if(!['http:','https:'].includes(u.protocol))throw new Error('Only http/https URLs are supported');const addrs=await dns.lookup(u.hostname,{all:true});if(!addrs.length||addrs.some(a=>isPrivate(a.address)))throw new Error('Private or unresolved destination');return u}
function plain(html:string){return html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&[a-z#0-9]+;/gi,' ').replace(/\s+/g,' ').trim()}
function meta(html:string,name:string){const esc=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const a=new RegExp(`<meta[^>]+(?:name|property)=["']${esc}["'][^>]+content=["']([^"']*)["'][^>]*>`,`i`).exec(html);const b=new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+(?:name|property)=["']${esc}["'][^>]*>`,`i`).exec(html);return (a?.[1]||b?.[1]||'').trim()||null}
function platform(html:string){if(/cdn\.shopify\.com|Shopify\.theme|shopify-section/i.test(html))return 'Shopify';if(/salla\.sa|salla\.cloud|salla-/i.test(html))return 'Salla';if(/zid\.store|zid\.sa/i.test(html))return 'Zid';if(/woocommerce|wp-content\/plugins\/woocommerce/i.test(html))return 'WooCommerce';return null}
const STOP=new Set('the and with from this that your our shop store online new best buy for you are all more collection collections product products home sale discover explore women woman men man kids about shipping return returns contact policy سياسة متجر تسوق متجرنا منتجات منتج جديد جديده الجديدة للنساء للرجال من على في الى إلى عن مع هذا هذه'.split(/\s+/));
function tokens(s:string){return s.toLowerCase().replace(/[^\p{L}\p{N}\s-]/gu,' ').split(/\s+/).map(x=>x.trim()).filter(x=>x.length>=3&&!STOP.has(x)&&!/^[0-9]+$/.test(x))}
function topTokens(s:string,limit=24){const m=new Map<string,number>();for(const t of tokens(s))m.set(t,(m.get(t)||0)+1);return [...m].sort((a,b)=>b[1]-a[1]).slice(0,limit).map(x=>x[0])}
function structuredProductTerms(html:string){const names=[...html.matchAll(/["']name["']\s*:\s*["']([^"']{3,90})["']/gi)].slice(0,120).map(x=>x[1]);return [...new Set(names.flatMap(tokens))].slice(0,40)}
function getPrices(body:string){const arr:number[]=[];const re=/(?:SAR|AED|USD|EGP|KWD|QAR|BHD|ر\.س|د\.إ|ج\.م|جنيه|LE|E£|\$)\s*([0-9][0-9,.]*)|([0-9][0-9,.]*)\s*(?:SAR|AED|USD|EGP|KWD|QAR|BHD|ر\.س|د\.إ|ج\.م|جنيه|LE|E£)/gi;for(const x of body.matchAll(re)){const n=Number((x[1]||x[2]||'').replace(/,/g,''));if(Number.isFinite(n)&&n>0&&n<1000000)arr.push(n)}return arr.sort((a,b)=>a-b)}
function currencies(body:string){const out:string[]=[];for(const [r,c] of [[/SAR|ر\.س/gi,'SAR'],[/AED|د\.إ/gi,'AED'],[/EGP|ج\.م|جنيه مصري|E£/gi,'EGP'],[/KWD|د\.ك/gi,'KWD'],[/QAR|ر\.ق/gi,'QAR'],[/BHD|د\.ب/gi,'BHD'],[/USD|\$/gi,'USD']] as const)if(r.test(body))out.push(c);return out}
const MARKET_RULES:[string,RegExp[],string[]][]=[
 ['Egypt',[/\bEgypt\b|\bCairo\b|\bAlexandria\b|مصر|القاهرة|الإسكندرية|\+20\s?/i],['EGP']],
 ['Saudi Arabia',[/Saudi Arabia|\bKSA\b|Riyadh|Jeddah|السعودية|الرياض|جدة|\+966/i],['SAR']],
 ['UAE',[/United Arab Emirates|\bUAE\b|Dubai|Abu Dhabi|الإمارات|دبي|أبوظبي|\+971/i],['AED']],
 ['Kuwait',[/\bKuwait\b|الكويت|\+965/i],['KWD']],
 ['Qatar',[/\bQatar\b|Doha|قطر|الدوحة|\+974/i],['QAR']],
 ['Bahrain',[/\bBahrain\b|البحرين|\+973/i],['BHD']]
];
function inferMarket(host:string,body:string,cur:string[]){const score=new Map<string,number>();const evidence=new Map<string,string[]>();const add=(m:string,n:number,e:string)=>{score.set(m,(score.get(m)||0)+n);evidence.set(m,[...(evidence.get(m)||[]),e])};
 const tld=host.split('.').pop()?.toLowerCase();const tldMap:any={eg:'Egypt',sa:'Saudi Arabia',ae:'UAE',kw:'Kuwait',qa:'Qatar',bh:'Bahrain'};if(tld&&tldMap[tld])add(tldMap[tld],45,`.${tld} country domain`);
 for(const [market,patterns,curs] of MARKET_RULES){for(const c of curs)if(cur.includes(c))add(market,40,`${c} currency detected`);for(const p of patterns)if(p.test(body.slice(0,220000)))add(market,22,`${market} location/contact signal detected`)}
 const ranked=[...score.entries()].sort((a,b)=>b[1]-a[1]);const primary=ranked[0]?.[0]||null;const raw=ranked[0]?.[1]||0;const confidence=Math.min(100,raw);return {primary,confidence,evidence:primary?[...new Set(evidence.get(primary)||[])]:[],hints:ranked.filter(x=>x[1]>=20).map(x=>x[0])}}
function languageFamily(lang:string|null,body:string){const ar=(body.match(/[\u0600-\u06FF]/g)||[]).length;const latin=(body.match(/[A-Za-z]/g)||[]).length;const l=(lang||'').toLowerCase();if(l.startsWith('ar')&&latin>1000)return 'Mixed' as const;if(l.startsWith('ar')||ar>latin*.35)return 'Arabic' as const;if(l.startsWith('en')||latin>ar*4)return 'English' as const;if(ar>500&&latin>500)return 'Mixed' as const;return 'Unknown' as const}
function shippingMarkets(body:string){const shippingWindow=(body.match(/.{0,180}(?:shipping|delivery|نشحن|الشحن|التوصيل).{0,300}/gi)||[]).join(' ');const out:string[]=[];for(const [market,patterns] of MARKET_RULES)if(patterns.some(p=>p.test(shippingWindow)))out.push(market);return [...new Set(out)]}
function addressSignals(body:string){const out:string[]=[];for(const [market,patterns] of MARKET_RULES)if(patterns.some(p=>p.test(body.slice(0,300000))))out.push(market);return [...new Set(out)]}
function productSamples(html:string,cur:string[]):ProductSample[]{const out:ProductSample[]=[];const jsonNames=[...html.matchAll(/["']name["']\s*:\s*["']([^"']{3,100})["']/gi)].slice(0,20).map(x=>x[1]);for(const name of jsonNames){if(out.some(x=>x.name===name))continue;out.push({name:name.trim(),price:null,currency:cur[0]||null});if(out.length>=8)break}return out}
function categoryLabels(html:string){const raw=[...html.matchAll(/<a[^>]+href=["'][^"']*(?:collections?|categor(?:y|ies)|shop\/)[^"']*["'][^>]*>([\s\S]*?)<\/a>/gi)].map(x=>plain(x[1])).filter(x=>x.length>=2&&x.length<=60);return [...new Set(raw)].slice(0,18)}
export async function understandStore(raw:string):Promise<StoreProfile>{const u=await publicUrl(raw);const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),15000);try{const res=await fetch(u,{redirect:'follow',signal:ctrl.signal,headers:{'user-agent':'NOVA-ResearchBot/1.1','accept':'text/html'}});if(!res.ok)throw new Error(`Store returned HTTP ${res.status}`);const html=(await res.text()).slice(0,2_500_000);const body=plain(html);const t=/<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1]?.replace(/\s+/g,' ').trim()||null;const desc=meta(html,'description')||meta(html,'og:description');const lang=/<html[^>]+lang=["']([^"']+)/i.exec(html)?.[1]||null;const prices=getPrices(body);const keywords=topTokens(`${t||''} ${desc||''} ${body.slice(0,100000)}`);const productTerms=structuredProductTerms(html);const labels=categoryLabels(html);const categories=labels.length?labels:[...new Set([...html.matchAll(/href=["'][^"']*(?:collection|categor|shop)[^"']*["'][^>]*>([^<]{2,60})</gi)].map(x=>plain(x[1])).filter(Boolean).flatMap(tokens))].slice(0,20);const cur=currencies(body);const market=inferMarket(u.hostname,body,cur);const shipping=shippingMarkets(body);const addresses=addressSignals(body);const langFamily=languageFamily(lang,body);return {url:res.url||u.toString(),domain:new URL(res.url||u.toString()).hostname.replace(/^www\./,''),title:t,description:desc,language:lang,platform:platform(html),currencies:cur,priceMin:prices.length?prices[Math.floor(prices.length*.1)]:null,priceMax:prices.length?prices[Math.floor(prices.length*.9)]:null,priceMedian:prices.length?prices[Math.floor(prices.length*.5)]:null,keywords,categories,productTerms,productSamples:productSamples(html,cur),marketHints:market.hints,primaryMarket:market.primary,marketConfidence:market.confidence,marketEvidence:market.evidence,shippingMarkets:shipping,addressSignals:addresses,languageFamily:langFamily,evidence:[`${keywords.length} commercial/content keywords extracted`,`${categories.length} category labels extracted`,`${productTerms.length} product terms extracted`,prices.length?`${prices.length} price signals sampled`:'No reliable price sample',cur.length?`Currencies detected: ${cur.join(', ')}`:'Currency not proven',market.primary?`Primary market: ${market.primary} (${market.confidence}% confidence)`:'Primary market not proven',`Language profile: ${langFamily}`]};}finally{clearTimeout(timer)}}
