import 'server-only';
import dns from 'node:dns/promises';
import net from 'node:net';

export type StoreProfile={
 url:string; domain:string; title:string|null; description:string|null; language:string|null; platform:string|null;
 currencies:string[]; priceMin:number|null; priceMax:number|null; priceMedian:number|null;
 keywords:string[]; categories:string[]; productTerms:string[]; marketHints:string[];
 evidence:string[];
};
const PRIVATE=[/^10\./,/^127\./,/^169\.254\./,/^192\.168\./,/^172\.(1[6-9]|2\d|3[01])\./,/^0\./];
function isPrivate(ip:string){if(net.isIPv4(ip))return PRIVATE.some(r=>r.test(ip));if(net.isIPv6(ip))return ip==='::1'||ip.startsWith('fc')||ip.startsWith('fd')||ip.startsWith('fe80:');return true}
async function publicUrl(raw:string){const u=new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`);if(!['http:','https:'].includes(u.protocol))throw new Error('Only http/https URLs are supported.');const addrs=await dns.lookup(u.hostname,{all:true});if(!addrs.length||addrs.some(a=>isPrivate(a.address)))throw new Error('Private or unresolved destination.');return u}
function plain(html:string){return html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&[a-z#0-9]+;/gi,' ').replace(/\s+/g,' ').trim()}
function meta(html:string,name:string){const esc=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const a=new RegExp(`<meta[^>]+(?:name|property)=["']${esc}["'][^>]+content=["']([^"']*)["'][^>]*>`,`i`).exec(html);const b=new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+(?:name|property)=["']${esc}["'][^>]*>`,`i`).exec(html);return (a?.[1]||b?.[1]||'').trim()||null}
function platform(html:string){if(/cdn\.shopify\.com|Shopify\.theme|shopify-section/i.test(html))return 'Shopify';if(/salla\.sa|salla\.cloud|salla-/i.test(html))return 'Salla';if(/zid\.store|zid\.sa/i.test(html))return 'Zid';if(/woocommerce|wp-content\/plugins\/woocommerce/i.test(html))return 'WooCommerce';return null}
const STOP=new Set('the and with from this that your our shop store online new best buy for you are all more collection collections product products home sale discover explore women woman men man kids about shipping return returns contact سياسة متجر تسوق متجرنا منتجات منتج جديد جديده الجديدة للنساء للرجال من على في الى إلى عن مع هذا هذه'.split(/\s+/));
function tokens(s:string){return s.toLowerCase().replace(/[^\p{L}\p{N}\s-]/gu,' ').split(/\s+/).map(x=>x.trim()).filter(x=>x.length>=3&&!STOP.has(x)&&!/^[0-9]+$/.test(x))}
function topTokens(s:string,limit=24){const m=new Map<string,number>();for(const t of tokens(s))m.set(t,(m.get(t)||0)+1);return [...m].sort((a,b)=>b[1]-a[1]).slice(0,limit).map(x=>x[0])}
function structuredProductTerms(html:string){const names=[...html.matchAll(/["']name["']\s*:\s*["']([^"']{3,90})["']/gi)].slice(0,80).map(x=>x[1]);return [...new Set(names.flatMap(tokens))].slice(0,32)}
function getPrices(body:string){const arr:number[]=[];const re=/(?:SAR|AED|USD|EGP|ر\.س|د\.إ|ج\.م|\$)\s*([0-9][0-9,.]*)|([0-9][0-9,.]*)\s*(?:SAR|AED|USD|EGP|ر\.س|د\.إ|ج\.م)/gi;for(const x of body.matchAll(re)){const n=Number((x[1]||x[2]||'').replace(/,/g,''));if(Number.isFinite(n)&&n>0&&n<1000000)arr.push(n)}return arr.sort((a,b)=>a-b)}
function currencies(body:string){const out:string[]=[];for(const [r,c] of [[/SAR|ر\.س/gi,'SAR'],[/AED|د\.إ/gi,'AED'],[/EGP|ج\.م/gi,'EGP'],[/USD|\$/gi,'USD']] as const)if(r.test(body))out.push(c);return out}
export async function understandStore(raw:string):Promise<StoreProfile>{const u=await publicUrl(raw);const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),15000);try{const res=await fetch(u,{redirect:'follow',signal:ctrl.signal,headers:{'user-agent':'NOVA-ResearchBot/1.0','accept':'text/html'}});if(!res.ok)throw new Error(`Store returned HTTP ${res.status}.`);const html=(await res.text()).slice(0,2_500_000);const body=plain(html);const t=/<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1]?.replace(/\s+/g,' ').trim()||null;const desc=meta(html,'description')||meta(html,'og:description');const lang=/<html[^>]+lang=["']([^"']+)/i.exec(html)?.[1]||null;const prices=getPrices(body);const keywords=topTokens(`${t||''} ${desc||''} ${body.slice(0,80000)}`);const productTerms=structuredProductTerms(html);const categoryLinks=[...html.matchAll(/href=["'][^"']*(?:collection|categor|shop)[^"']*["'][^>]*>([^<]{2,60})</gi)].map(x=>plain(x[1])).filter(Boolean).slice(0,30);const categories=[...new Set(categoryLinks.flatMap(tokens))].slice(0,20);const cur=currencies(body);const hints=[u.hostname.split('.').pop()==='sa'?'Saudi Arabia':'',u.hostname.split('.').pop()==='ae'?'UAE':'',cur.includes('SAR')?'Saudi Arabia':'',cur.includes('AED')?'UAE':'',cur.includes('EGP')?'Egypt':''].filter(Boolean);return {url:res.url||u.toString(),domain:new URL(res.url||u.toString()).hostname.replace(/^www\./,''),title:t,description:desc,language:lang,platform:platform(html),currencies:cur,priceMin:prices.length?prices[Math.floor(prices.length*.1)]:null,priceMax:prices.length?prices[Math.floor(prices.length*.9)]:null,priceMedian:prices.length?prices[Math.floor(prices.length*.5)]:null,keywords,categories,productTerms,marketHints:[...new Set(hints)],evidence:[`${keywords.length} commercial/content keywords extracted`,`${categories.length} category terms extracted`,`${productTerms.length} product terms extracted`,prices.length?`${prices.length} price signals sampled`:'No reliable price sample',cur.length?`Currencies detected: ${cur.join(', ')}`:'Currency not proven']};}finally{clearTimeout(timer)}}
