type Input={projectName:string;latestScore:number|null;competitors:any[];opportunities:any[];changes:any[];ownProfile:any;pricing:any;assortment:any[]};
const n=(v:any)=>Number.isFinite(Number(v))?Number(v):null;
const pct=(v:any)=>n(v)==null?'—':`${Math.round(Number(v))}%`;
export function analystAnswer(question:string,input:Input){
 const q=question.trim().toLowerCase();const comps=[...input.competitors].filter(x=>x.status!=='rejected').sort((a,b)=>(b.match_score||0)-(a.match_score||0));const direct=comps.filter(x=>/direct|strong/i.test(String(x.classification||'')));const opps=[...input.opportunities].filter(x=>x.status!=='dismissed').sort((a,b)=>(b.decision_score??b.priority??0)-(a.decision_score??a.priority??0));const changes=[...input.changes].slice(0,12);const evidenceHealth=Math.round(((input.latestScore!=null?80:20)+(comps.length?Math.min(100,45+comps.length*10):15)+(input.ownProfile?.primaryMarket?85:25)+(input.ownProfile?.taxonomyConfidence||20))/4);
 if(!q)return {title:`NOVA Analyst · ${input.projectName}`,answer:`Project evidence health is ${evidenceHealth}%. Ask a focused question about competitors, pricing, recent changes, products or the next action to take`,evidence:[`${comps.length} validated competitor profiles`,`${opps.length} open opportunities`,`${changes.length} recent monitoring events`],confidence:evidenceHealth,followups:['What should I test first?','Who is my closest direct competitor?','Where is my evidence weak?']};
 if(/closest|competitor|منافس/.test(q)){const c=direct[0]||comps[0];return c?{title:direct[0]?'Closest meaningful competitor':'Closest available competitor',answer:`${c.name||c.store_url} is currently the strongest validated match at ${pct(c.match_score)} with ${pct(c.confidence_score)} evidence confidence${direct[0]?' and passes the current direct/strong qualification gate':' but NOVA does not yet have a stronger direct-qualified option'}`,evidence:[`Classification: ${c.classification||'Unclassified'}`,`Market: ${c.profile?.primaryMarket||'Not proven'}`,`Validated set: ${comps.length} profiles`],confidence:Math.min(Number(c.confidence_score||0),Number(c.match_score||0)),followups:['Why is this competitor considered relevant?','How do our prices compare?','What should I learn from this competitor?']}:{title:'Competitor evidence is still thin',answer:'Validate or discover competitors first so NOVA can rank a meaningful local match',evidence:[],confidence:20,followups:['How do I improve competitor discovery?']}}
 if(/price|pricing|overpriced|سعر|اسعار/.test(q)){const c=input.pricing?.comparableCount||direct.filter(x=>x.profile?.priceMedian).length;return {title:'Pricing position',answer:input.pricing.delta==null?'NOVA does not have enough same-currency comparable price evidence yet':`Your visible median price is ${Math.abs(input.pricing.delta)}% ${input.pricing.delta>0?'above':'below'} the validated competitor median, which currently positions you as ${String(input.pricing.label||'market-aligned').toLowerCase()}`,evidence:input.pricing.marketMedian?[`Competitor median: ${Math.round(input.pricing.marketMedian).toLocaleString()}`,`Your detected median: ${Math.round(input.ownProfile?.priceMedian||0).toLocaleString()}`,`${c||0} comparable competitor price profiles`]:[],confidence:input.pricing.delta==null?30:Math.min(90,55+(c||1)*8),followups:['Which competitor is cheapest?','What pricing gap should I test?']}}
 if(/change|week|monitor|changed|تغير/.test(q)){return {title:'Recent competitor movement',answer:changes.length?`${changes.length} recent monitoring events are available. The latest signal is: ${changes[0].summary}`:'No competitor changes have been recorded yet',evidence:changes.slice(0,5).map(x=>`${x.kind}: ${x.summary}`),confidence:changes.length?Math.min(90,50+changes.length*5):25,followups:['Which change matters most?','What should I respond to first?']}}
 if(/test|opportun|first|priority|فرص|اختبار/.test(q)){const o=opps[0];return o?{title:'Highest-priority action',answer:`Start with “${o.title}”. NOVA ranks it at ${o.decision_score??o.priority??'—'} based on impact, confidence and estimated effort`,evidence:[String(o.evidence?.store||'Verified store finding'),String(o.evidence?.competitive||'Competitive evidence available')],confidence:Number(o.confidence||o.evidence?.confidence||70),followups:['Why is this the first priority?','What is the lowest-effort quick win?']}:{title:'No ranked opportunities yet',answer:'Run a benchmark to create evidence-backed opportunities before choosing what to test',evidence:[],confidence:20,followups:['How do I create benchmark evidence?']}}
 if(/category|assort|product|تصنيف|منتج/.test(q)){return {title:'Assortment intelligence',answer:input.assortment.length?`NOVA found ${input.assortment.length} recurring competitor categories that are not proven in your current category set`:'No recurring assortment gap is proven yet',evidence:input.assortment.slice(0,6).map(x=>`${x.category} appears across ${x.count} competitors`),confidence:input.assortment.length?Math.min(88,50+input.assortment.length*5):30,followups:['Which category appears most often?','How broad is my assortment vs competitors?']}}
 if(/weak|evidence|confidence|quality|ثقة|دليل/.test(q)){const gaps=[] as string[];if(!input.ownProfile?.primaryMarket)gaps.push('Primary market is not proven');if(!input.ownProfile?.taxonomyConfidence||input.ownProfile.taxonomyConfidence<60)gaps.push('Store taxonomy confidence is weak');if(comps.length<3)gaps.push('Fewer than 3 validated competitors');if(input.latestScore==null)gaps.push('No verified audit baseline');return {title:'Evidence quality check',answer:gaps.length?`NOVA found ${gaps.length} evidence gaps that can materially weaken recommendations`:'The project has a healthy evidence base for the current features',evidence:gaps.length?gaps:[`${comps.length} competitors validated`,`Market: ${input.ownProfile?.primaryMarket}`,`Taxonomy confidence: ${pct(input.ownProfile?.taxonomyConfidence)}`],confidence:evidenceHealth,followups:['What should I fix first?','How can I improve competitor confidence?']}}
 return {title:`NOVA Analyst · ${input.projectName}`,answer:`Current evidence health is ${evidenceHealth}%. NOVA has ${comps.length} validated competitors, ${opps.length} open opportunities and ${changes.length} recent competitor changes. Rephrase the question around competitors, pricing, changes, products, evidence quality or what to test first`,evidence:[],confidence:evidenceHealth,followups:['What should I test first?','Who is my closest competitor?','Where is my evidence weak?']};
}
