type Input={projectName:string;latestScore:number|null;competitors:any[];opportunities:any[];changes:any[];ownProfile:any;pricing:any;assortment:any[]};
export function analystAnswer(question:string,input:Input){
 const q=question.toLowerCase();const comps=[...input.competitors].sort((a,b)=>(b.match_score||0)-(a.match_score||0));const opps=[...input.opportunities].filter(x=>x.status!=='dismissed').sort((a,b)=>(b.decision_score??b.priority??0)-(a.decision_score??a.priority??0));const changes=[...input.changes].slice(0,8);
 if(/closest|competitor|منافس/.test(q)){const c=comps[0];return c?{title:'Closest validated competitor',answer:`${c.name||c.store_url} is currently the closest validated competitor at ${c.match_score}% match with ${c.confidence_score}% evidence confidence`,evidence:[`Classification: ${c.classification}`,`Validated competitor set: ${comps.length}`]}:{title:'Competitor evidence is still thin',answer:'Validate or discover competitors first so NOVA can rank the closest match',evidence:[]}}
 if(/price|pricing|overpriced|سعر|اسعار/.test(q)){return {title:'Pricing position',answer:input.pricing.delta==null?'NOVA does not have enough comparable price evidence yet':`Your visible median price is ${Math.abs(input.pricing.delta)}% ${input.pricing.delta>0?'above':'below'} the validated competitor median, which currently positions you as ${input.pricing.label.toLowerCase()}`,evidence:input.pricing.marketMedian?[`Competitor median: ${Math.round(input.pricing.marketMedian).toLocaleString()}`,`Your detected median: ${Math.round(input.ownProfile?.priceMedian||0).toLocaleString()}`]:[]}}
 if(/change|week|monitor|changed|تغير/.test(q)){return {title:'Recent competitor movement',answer:changes.length?`${changes.length} recent monitoring events are available. The latest signal is: ${changes[0].summary}`:'No competitor changes have been recorded yet',evidence:changes.slice(0,5).map(x=>`${x.kind}: ${x.summary}`)}}
 if(/test|opportun|first|priority|فرص|اختبار/.test(q)){const o=opps[0];return o?{title:'Highest-priority action',answer:`Start with “${o.title}”. NOVA ranks it at ${o.decision_score??o.priority??'—'} based on impact, confidence and estimated effort`,evidence:[String(o.evidence?.store||'Verified store finding'),String(o.evidence?.competitive||'Competitive evidence available')]}:{title:'No ranked opportunities yet',answer:'Run a benchmark to create evidence-backed opportunities',evidence:[]}}
 if(/category|assort|product|تصنيف|منتج/.test(q)){return {title:'Assortment intelligence',answer:input.assortment.length?`NOVA found ${input.assortment.length} recurring competitor categories that are not proven in your current category set`:'No recurring assortment gap is proven yet',evidence:input.assortment.slice(0,6).map(x=>`${x.category} appears across ${x.count} competitors`)}}
 return {title:`NOVA Analyst · ${input.projectName}`,answer:`Current evidence: NOVA Score ${input.latestScore??'not available'}, ${comps.length} validated competitors, ${opps.length} open opportunities and ${changes.length} recorded competitor changes. Ask about competitors, pricing, changes, products or what to test first`,evidence:[]};
}
