'use server';
import {redirect} from 'next/navigation';import {revalidatePath} from 'next/cache';import {createSupabaseServerClient} from '../../lib/supabase/server';import {understandStore} from '../../lib/competitors/store-intelligence';import {compareStores} from '../../lib/competitors/scoring';import {discoverCandidates,isDiscoveryConfigured} from '../../lib/competitors/discovery';
async function context(projectId:string){const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const {data:store}=await supabase.from('stores').select('id,url,profile').eq('project_id',projectId).limit(1).maybeSingle();if(!store)throw new Error('No connected store.');let profile:any=store.profile;if(!profile||!Object.keys(profile).length||profile.primaryMarket===undefined||profile.marketConfidence===undefined){profile=await understandStore(store.url);await supabase.from('stores').update({profile,profile_updated_at:new Date().toISOString(),platform:profile.platform||undefined,currency:profile.currencies?.[0]||undefined,market:profile.marketHints?.[0]||undefined}).eq('id',store.id)}return {supabase,store,profile}}
async function validate(projectId:string,url:string,source='manual',searchOverlap:number|null=null){const {supabase,profile}=await context(projectId);const candidate=await understandStore(url);if(candidate.domain===profile.domain)throw new Error('Candidate cannot be the project store itself.');const scored=compareStores(profile,candidate,searchOverlap);const row={project_id:projectId,store_url:candidate.url,normalized_url:`https://${candidate.domain}`,name:candidate.title||candidate.domain,classification:scored.classification,match_score:scored.match,confidence_score:scored.confidence,signals:scored.signals,profile:candidate,source,evidence:scored.evidence,status:['Global Reference','Needs Verification'].includes(scored.classification)?'review':'validated',validated_at:new Date().toISOString()};const {error}=await supabase.from('competitors').upsert(row,{onConflict:'project_id,normalized_url'});if(error)throw error;await supabase.from('notifications').insert({project_id:projectId,kind:'workflow',title:'Competitor validated',body:`${candidate.title||candidate.domain} scored ${scored.match}% match with ${scored.confidence}% confidence`,href:`/projects/${projectId}/competitors`});return scored}
export async function addCompetitor(projectId:string,formData:FormData){const raw=String(formData.get('url')||'').trim();if(!raw)redirect(`/projects/${projectId}/competitors?error=${encodeURIComponent('Enter a competitor URL.')}`);try{await validate(projectId,raw)}catch(e){redirect(`/projects/${projectId}/competitors?error=${encodeURIComponent(e instanceof Error?e.message:'Validation failed.')}`)}revalidatePath(`/projects/${projectId}/competitors`);revalidatePath(`/projects/${projectId}`);redirect(`/projects/${projectId}/competitors?added=1`)}
export async function discoverProjectCompetitors(projectId:string){if(!isDiscoveryConfigured())redirect(`/projects/${projectId}/competitors?error=${encodeURIComponent('Automatic discovery is disabled. Manual competitor validation is available now.')}`);let count=0;try{const {profile,supabase}=await context(projectId);const cache={
  get:async(key:string)=>{const {data}=await supabase.from('discovery_search_cache').select('results,expires_at').eq('cache_key',`${projectId}:${key}`).gt('expires_at',new Date().toISOString()).maybeSingle();return Array.isArray((data as any)?.results)?(data as any).results:null},
  getStale:async(key:string)=>{const {data}=await supabase.from('discovery_search_cache').select('results').eq('cache_key',`${projectId}:${key}`).order('updated_at',{ascending:false}).limit(1).maybeSingle();return Array.isArray((data as any)?.results)?(data as any).results:null},
  set:async(key:string,rows:any[],ttlHours:number)=>{await supabase.from('discovery_search_cache').upsert({cache_key:`${projectId}:${key}`,project_id:projectId,results:rows,updated_at:new Date().toISOString(),expires_at:new Date(Date.now()+ttlHours*3600_000).toISOString()},{onConflict:'cache_key'})}
};
const candidates=await discoverCandidates(profile,cache);count=candidates.length;const {data:existing}=await supabase.from('competitors').select('normalized_url,validated_at').eq('project_id',projectId);const recent=new Map<string,number>((existing||[]).map((x:any)=>[String(x.normalized_url),new Date(x.validated_at||0).getTime()] as [string,number]));for(const c of candidates.slice(0,10)){try{const normalized=`https://${new URL(c.url).hostname.replace(/^www\./,'')}`;if(Date.now()-(recent.get(normalized)||0)<24*3600_000)continue;const overlap=Math.min(1,Math.max(.08,(c.preScore/100)*.55+Math.min(.3,c.queryHits*.08)));await validate(projectId,c.url,`${c.source}:${c.scope}:q${c.queryHits}:pre${c.preScore}:ai${c.aiProvider||'none'}`,overlap)}catch{}}revalidatePath(`/projects/${projectId}/competitors`)}catch(e){redirect(`/projects/${projectId}/competitors?error=${encodeURIComponent(e instanceof Error?e.message:'Discovery failed.')}`)}redirect(`/projects/${projectId}/competitors?discovered=${count}`)}
export async function refreshStoreProfile(projectId:string){try{const {supabase,store}=await context(projectId);const profile=await understandStore(store.url);await supabase.from('stores').update({profile,profile_updated_at:new Date().toISOString(),platform:profile.platform||undefined,currency:profile.currencies?.[0]||undefined,market:profile.marketHints?.[0]||undefined}).eq('id',store.id);revalidatePath(`/projects/${projectId}/competitors`)}catch(e){redirect(`/projects/${projectId}/competitors?error=${encodeURIComponent(e instanceof Error?e.message:'Store understanding failed.')}`)}redirect(`/projects/${projectId}/competitors?profile=1`)}
export async function deleteCompetitor(projectId:string,competitorId:string){const supabase=await createSupabaseServerClient();await supabase.from('competitors').delete().eq('id',competitorId).eq('project_id',projectId);revalidatePath(`/projects/${projectId}/competitors`)}
