export const DEFAULT_WEIGHTS=Object.freeze({marketOverlap:.28,categoryOverlap:.20,productSimilarity:.16,priceSimilarity:.12,currencyMatch:.08,languageMatch:.06,searchOverlap:.06,audienceSimilarity:.04});
const clamp=n=>Math.max(0,Math.min(1,Number(n)||0));
export function classifyCompetitor(score,marketOverlap=null){if(marketOverlap!=null&&marketOverlap>=.8&&score>=76)return 'Local Direct';if(marketOverlap!=null&&marketOverlap>=.8&&score>=62)return 'Local Strong';if(score>=64)return 'Regional Strong';if(score>=48)return 'Adjacent';return 'Global Reference'}
const S=xs=>new Set((xs||[]).map(x=>String(x).toLowerCase().trim()).filter(Boolean));
export function jaccard(a=[],b=[]){const A=S(a),B=S(b);if(!A.size||!B.size)return null;let hit=0;for(const x of A)if(B.has(x))hit++;return hit/(A.size+B.size-hit)}
export function fuzzyOverlap(a=[],b=[]){if(!a.length||!b.length)return null;const A=a.map(x=>String(x).toLowerCase()),B=b.map(x=>String(x).toLowerCase());let hit=0;for(const x of A)if(B.some(y=>x===y||x.includes(y)||y.includes(x)))hit++;return Math.min(1,hit/Math.max(1,Math.min(A.length,B.length)))}
export function priceSimilarity(a,b,sameCurrency=true){if(!a||!b||!sameCurrency)return null;return Math.max(0,Math.min(1,Math.min(a,b)/Math.max(a,b)))}
export function scoreCompetitor(signals={},context={},weights=DEFAULT_WEIGHTS){let available=0,weighted=0;for(const [key,w] of Object.entries(weights)){if(signals[key]!=null){available+=w;weighted+=clamp(signals[key])*w}}const hasQuality=context.crawlQuality!=null;const quality=clamp((context.crawlQuality??0)/100);let confidence=Math.round(Math.min(1,available*.78+(hasQuality?quality*.22:0))*100);let match=available?Math.round(weighted/available*100):0;const market=signals.marketOverlap,cat=signals.categoryOverlap??0,prod=signals.productSimilarity??0;const sameMarket=market!=null&&market>=.8,differentMarket=market!=null&&market<=.12;const directGate=sameMarket&&cat>=.32&&prod>=.22&&confidence>=55;if(hasQuality&&quality<.35){match=Math.min(match,72);confidence=Math.min(confidence,58)}if(differentMarket)match=Math.min(match,52);if(differentMarket&&signals.currencyMatch===0)match=Math.min(match,42);if(cat<.12&&prod<.12)match=Math.min(match,48);const insufficient=confidence<35||(signals.categoryOverlap==null&&signals.productSimilarity==null);let classification;if(insufficient)classification='Needs Verification';else if(directGate&&match>=76)classification='Local Direct';else if(sameMarket&&cat>=.22&&confidence>=45&&match>=62)classification='Local Strong';else if(!sameMarket&&match>=64&&cat>=.3)classification='Regional Strong';else if(match>=48)classification='Adjacent';else classification='Global Reference';return {match,confidence,classification,confidenceLabel:confidence>=80?'High':confidence>=55?'Medium':'Low',directGate}}
export function compareProfiles(a={},b={},searchOverlap=null){const ac=S(a.currencies),bc=S(b.currencies),ah=S(a.marketHints),bh=S(b.marketHints);const marketOverlap=a.primaryMarket&&b.primaryMarket?a.primaryMarket===b.primaryMarket?1:.02:(ah.size&&bh.size?[...ah].some(x=>bh.has(x))?.85:.08:ac.size&&bc.size?[...ac].some(x=>bc.has(x))?1:0:null);const currencyMatch=ac.size&&bc.size?[...ac].some(x=>bc.has(x))?1:0:null;const languageMatch=a.languageFamily&&b.languageFamily&&a.languageFamily!=='Unknown'&&b.languageFamily!=='Unknown'?(a.languageFamily===b.languageFamily?1:((a.languageFamily==='Mixed'||b.languageFamily==='Mixed')?.7:.1)):null;const sameCurrency=currencyMatch!==0;const signals={marketOverlap,categoryOverlap:fuzzyOverlap(a.categories?.length?a.categories:a.keywords,b.categories?.length?b.categories:b.keywords),productSimilarity:fuzzyOverlap(a.productTerms?.length?a.productTerms:a.keywords,b.productTerms?.length?b.productTerms:b.keywords),priceSimilarity:priceSimilarity(a.priceMedian,b.priceMedian,sameCurrency),currencyMatch,languageMatch,searchOverlap,audienceSimilarity:jaccard((a.keywords||[]).slice(0,20),(b.keywords||[]).slice(0,20))};const crawlQuality=Math.min(a.crawlCoverage??100,b.crawlCoverage??100);const scored=scoreCompetitor(signals,{crawlQuality});return {...scored,signals,evidence:[...Object.entries(signals).filter(([,v])=>v!=null).map(([k,v])=>`${k}: ${Math.round(Number(v)*100)}%`),`crawl evidence quality: ${crawlQuality}%`,`direct gate: ${scored.directGate?'passed':'not passed'}`]}}
