export const DEFAULT_WEIGHTS=Object.freeze({marketOverlap:.25,categoryOverlap:.20,priceSimilarity:.15,languageMatch:.10,currencyMatch:.10,productSimilarity:.10,searchOverlap:.05,audienceSimilarity:.05});
const clamp=n=>Math.max(0,Math.min(1,Number(n)||0));
export function scoreCompetitor(signals={},weights=DEFAULT_WEIGHTS){let total=0,available=0,weighted=0;for(const [key,w] of Object.entries(weights)){total+=w;if(signals[key]!=null){available+=w;weighted+=clamp(signals[key])*w}}let match=available?Math.round(weighted/available*100):0;const confidence=Math.round(total?available/total*100:0);const market=signals.marketOverlap;const currency=signals.currencyMatch;if(market!=null&&market<=.15)match=Math.min(match,currency===0?55:64);return {match,confidence,classification:classifyCompetitor(match,market),confidenceLabel:confidence>=80?'High':confidence>=55?'Medium':'Low'}}
export function classifyCompetitor(score,marketOverlap=null){if(marketOverlap!=null&&marketOverlap>=.8&&score>=80)return 'Local Direct';if(marketOverlap!=null&&marketOverlap>=.8&&score>=67)return 'Local Strong';if(score>=70)return 'Regional Strong';if(score>=50)return 'Adjacent';return 'Global Reference'}
const S=xs=>new Set((xs||[]).map(x=>String(x).toLowerCase().trim()).filter(Boolean));
export function jaccard(a=[],b=[]){const A=S(a),B=S(b);if(!A.size||!B.size)return null;let hit=0;for(const x of A)if(B.has(x))hit++;return hit/(A.size+B.size-hit)}
export function fuzzyOverlap(a=[],b=[]){if(!a.length||!b.length)return null;const A=a.map(x=>String(x).toLowerCase()),B=b.map(x=>String(x).toLowerCase());let hit=0;for(const x of A)if(B.some(y=>x===y||x.includes(y)||y.includes(x)))hit++;return Math.min(1,hit/Math.max(1,Math.min(A.length,B.length)))}
export function priceSimilarity(a,b){if(!a||!b)return null;return Math.max(0,Math.min(1,Math.min(a,b)/Math.max(a,b)))}
export function compareProfiles(a={},b={},searchOverlap=null){const ac=S(a.currencies),bc=S(b.currencies),ah=S(a.marketHints),bh=S(b.marketHints);const marketOverlap=a.primaryMarket&&b.primaryMarket?a.primaryMarket===b.primaryMarket?1:.05:(ah.size&&bh.size?[...ah].some(x=>bh.has(x))?.9:.1:ac.size&&bc.size?[...ac].some(x=>bc.has(x))?1:0:null);const currencyMatch=ac.size&&bc.size?[...ac].some(x=>bc.has(x))?1:0:null;const languageMatch=a.languageFamily&&b.languageFamily&&a.languageFamily!=='Unknown'&&b.languageFamily!=='Unknown'?(a.languageFamily===b.languageFamily?1:((a.languageFamily==='Mixed'||b.languageFamily==='Mixed')?0.7:0.15)):null;const signals={marketOverlap,categoryOverlap:fuzzyOverlap(a.categories?.length?a.categories:a.keywords,b.categories?.length?b.categories:b.keywords),priceSimilarity:priceSimilarity(a.priceMedian,b.priceMedian),languageMatch,currencyMatch,productSimilarity:fuzzyOverlap(a.productTerms?.length?a.productTerms:a.keywords,b.productTerms?.length?b.productTerms:b.keywords),searchOverlap,audienceSimilarity:jaccard((a.keywords||[]).slice(0,18),(b.keywords||[]).slice(0,18))};return {...scoreCompetitor(signals),signals,evidence:Object.entries(signals).filter(([,v])=>v!=null).map(([k,v])=>`${k}: ${Math.round(Number(v)*100)}%`)}}
